// ============================================================================
// EXTRACTED TEST FILE - AUTO-GENERATED
// ============================================================================
// This file was automatically generated from database structured_json data
// Generated on: 2025-09-01T22:43:40.167Z
// Widget Type: coordinatePlane
// Source: Real questions from database
//
// These tests use actual widget configurations extracted from production data
// to ensure comprehensive test coverage with realistic scenarios.
//
// DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten on regeneration
//
// Run tests: bun test tests/widgets/coordinate-plane.extracted.test.ts
// Update snapshots: bun test tests/widgets/coordinate-plane.extracted.test.ts --update-snapshots
// ============================================================================

import { expect, test } from "bun:test"
import type { z } from "zod"
import { generateCoordinatePlane, CoordinatePlaneComprehensivePropsSchema } from "@/lib/widgets/generators"

type CoordinatePlaneInput = z.input<typeof CoordinatePlaneComprehensivePropsSchema>


// Extracted from question: x8162ca287ecd407a
// Course: 6th grade math
// Exercise: Ratios on coordinate plane
// Widget key: coordinate_plane_empty
test("coordinate-plane - Ratios on coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 6,
		"min": -1,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 95,
		"min": -10,
		"label": "y",
		"tickInterval": 10,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x7af3956dfc88e036
// Course: 6th grade math
// Exercise: Ratios on coordinate plane
// Widget key: image_1
test("coordinate-plane - Ratios on coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 380,
	"xAxis": {
		"max": 10,
		"min": 0,
		"label": "Time, seconds",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 40,
		"min": 0,
		"label": "Distance, meters",
		"tickInterval": 5,
		"showGridLines": true
	},
	"height": 380,
	"points": [
		{
			"x": 2,
			"y": 18,
			"id": "p1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 3,
			"y": 27,
			"id": "p2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 4,
			"y": 36,
			"id": "p3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x7fef064a2899e61f
// Course: 6th grade math
// Exercise: Ratios on coordinate plane
// Widget key: image_1
test("coordinate-plane - Ratios on coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 380,
	"xAxis": {
		"max": 5,
		"min": 0,
		"label": "Layers",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 250,
		"min": 0,
		"label": "Bricks",
		"tickInterval": 50,
		"showGridLines": true
	},
	"height": 380,
	"points": [
		{
			"x": 2,
			"y": 100,
			"id": "p1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 3,
			"y": 150,
			"id": "p2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 4,
			"y": 200,
			"id": "p3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x80c8f6d7b84f6237
// Course: 6th grade math
// Exercise: Points on the coordinate plane
// Widget key: coordinate_plane_empty
test("coordinate-plane - Points on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 325,
	"xAxis": {
		"max": 6,
		"min": -6,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 6,
		"min": -6,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x12b80844841e694a
// Course: 6th grade math
// Exercise: Points on the coordinate plane
// Widget key: coordinate_plane_empty
test("coordinate-plane - Points on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 325,
	"xAxis": {
		"max": 5,
		"min": -5,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 5,
		"min": -5,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [
		{
			"x": 0,
			"y": 0,
			"id": "origin",
			"color": "#0c7f99",
			"label": "origin",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xe0942c18f0ff61da
// Course: 6th grade math
// Exercise: Points on the coordinate plane
// Widget key: coordinate_plane_empty
test("coordinate-plane - Points on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 325,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x5ca32a31bd8019a1
// Course: 6th grade math
// Exercise: Points on the coordinate plane
// Widget key: coordinate_plane_empty
test("coordinate-plane - Points on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 325,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x77f8f52306d7816c
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [
		{
			"id": "x-axis",
			"color": "#000000",
			"style": "solid",
			"equation": {
				"type": "slopeIntercept",
				"slope": 0,
				"yIntercept": 0
			}
		},
		{
			"id": "y-axis",
			"color": "#000000",
			"style": "solid",
			"equation": {
				"A": 1,
				"B": 0,
				"C": 0,
				"type": "standard"
			}
		}
	],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 2,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 2,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xfb6f8989bdcc6386
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x5153fc91404d48e6
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xe9c2095eb3a4b2eb
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x4dfd01c273d9be42
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0ab0213e4a437137
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x10a418f614b84945
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 8,
		"min": -8,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 8,
		"min": -8,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xaf5acb3a8cedffa3
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x052bdb6e56052cdb
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xbb17edb65603da67
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xb18b699f7769e711
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x71a4488d3d95206a
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x537a27c662daa9d7
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 7,
		"min": -7,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 7,
		"min": -7,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x21d48c12ac64a44b
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x19530bd5ce68991f
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 7,
		"min": -7,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 7,
		"min": -7,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x059a5f7522ef5a47
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xbb939b14175fc648
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xf9128dba71f4288e
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x1e5b3ee9ba3968ca
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": true,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x17cd38faad19f71f
// Course: 6th grade math
// Exercise: Quadrants on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrants on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 275,
	"xAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 5,
		"min": -5,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 275,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x746e761ee63e52a4
// Course: 6th grade math
// Exercise: Distance between points: vertical or horizontal
// Widget key: graph_initial
test("coordinate-plane - Distance between points vertical or horizontal", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -6,
			"y": -5,
			"id": "pt-c",
			"color": "#000000",
			"label": "C",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0711e6ae63700ab5
// Course: 6th grade math
// Exercise: Distance between points: vertical or horizontal
// Widget key: coordinate_plane_initial
test("coordinate-plane - Distance between points vertical or horizontal", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -6,
			"y": 0,
			"id": "B",
			"color": "#000000",
			"label": "B",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x067e3e95f42bd0c5
// Course: 6th grade math
// Exercise: Distance between points: vertical or horizontal
// Widget key: coordinate_plane_initial
test("coordinate-plane - Distance between points vertical or horizontal", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -4,
			"y": 1,
			"id": "D",
			"color": "#000000",
			"label": "D",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x73a831da4cc5d438
// Course: 6th grade math
// Exercise: Distance between points: vertical or horizontal
// Widget key: coordinate_plane_initial
test("coordinate-plane - Distance between points vertical or horizontal", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": 1,
			"y": 3,
			"id": "B",
			"color": "#000000",
			"label": "B",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0bd727c39829602d
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: coordinate_plane_empty
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x444d0678bef5498e
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: coordinate_plane_empty
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0c9e74efe84ad405
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: plane_initial
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 500,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 500,
	"points": [
		{
			"x": 5,
			"y": 5,
			"id": "p1",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 4,
			"id": "p2",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": -4.5,
			"y": -4,
			"id": "p3",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": 1,
			"y": -5,
			"id": "p4",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": 9,
			"y": 0,
			"id": "p5",
			"color": "#222",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0c9e74efe84ad405
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: polygon_choice_a
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 500,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 500,
	"points": [
		{
			"x": 5,
			"y": 5,
			"id": "p1",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 4,
			"id": "p2",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": -4.5,
			"y": -4,
			"id": "p3",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": 1,
			"y": -5,
			"id": "p4",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": 9,
			"y": 0,
			"id": "p5",
			"color": "#222",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"p3",
				"p2",
				"p1",
				"p5",
				"p4"
			],
			"fillColor": "#11accd26",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0c9e74efe84ad405
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: polygon_choice_b
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 500,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 500,
	"points": [
		{
			"x": 5,
			"y": 5,
			"id": "p1",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 4,
			"id": "p2",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": -4.5,
			"y": -4,
			"id": "p3",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": 1,
			"y": -5,
			"id": "p4",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": 9,
			"y": 0,
			"id": "p5",
			"color": "#222",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"p1",
				"p3",
				"p2",
				"p4",
				"p5"
			],
			"fillColor": "#11accd26",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0c9e74efe84ad405
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: polygon_choice_c
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 500,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 500,
	"points": [
		{
			"x": 5,
			"y": 5,
			"id": "p1",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 4,
			"id": "p2",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": -4.5,
			"y": -4,
			"id": "p3",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": 1,
			"y": -5,
			"id": "p4",
			"color": "#222",
			"label": "",
			"style": "closed"
		},
		{
			"x": 9,
			"y": 0,
			"id": "p5",
			"color": "#222",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"p2",
				"p5",
				"p1",
				"p4",
				"p3"
			],
			"fillColor": "#11accd26",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x464316abed728ee9
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: coordinate_plane_empty
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x08f2ede236e8a319
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: triangle_choice_a
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -8,
			"y": -5,
			"id": "A1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 1,
			"id": "A2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 6,
			"id": "A3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"A1",
				"A2",
				"A3"
			],
			"fillColor": "#11accd26",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x08f2ede236e8a319
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: triangle_choice_b
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -8,
			"y": -5,
			"id": "B1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": -1,
			"id": "B2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 6,
			"id": "B3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"B1",
				"B2",
				"B3"
			],
			"fillColor": "#11accd26",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x08f2ede236e8a319
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: triangle_choice_c
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -8,
			"y": -5,
			"id": "C1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 1,
			"id": "C2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -4,
			"y": 6,
			"id": "C3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"C1",
				"C2",
				"C3"
			],
			"fillColor": "#11accd26",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc27c078f05d13381
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: coordinate_plane_empty
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2139aff8c2468d19
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: graph_choice_a
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": 7,
			"y": -7,
			"id": "P1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 5,
			"y": 4,
			"id": "P2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 4,
			"id": "P3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": -4,
			"id": "P4",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"P1",
				"P2",
				"P3",
				"P4"
			],
			"fillColor": "#00000000",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2139aff8c2468d19
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: graph_choice_b
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": 7,
			"y": -7,
			"id": "P1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 5,
			"y": 4,
			"id": "P2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 4,
			"id": "P3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": -4,
			"id": "P4",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"P1",
				"P3",
				"P2",
				"P4"
			],
			"fillColor": "#00000000",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2139aff8c2468d19
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: graph_choice_c
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": 7,
			"y": 7,
			"id": "Q1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 5,
			"y": 4,
			"id": "Q2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 4,
			"id": "Q3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": -4,
			"id": "Q4",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"Q1",
				"Q2",
				"Q3",
				"Q4"
			],
			"fillColor": "#00000000",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2139aff8c2468d19
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: coordinate_plane_initial
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xd77f24f920e2355f
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: coordinate_plane_empty
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc9187daacca72603
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: triangle_initial
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc9187daacca72603
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: triangle_choice_a
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -9,
			"y": 4,
			"id": "p1",
			"color": "#1f77b4",
			"label": "A",
			"style": "closed"
		},
		{
			"x": -9,
			"y": 7,
			"id": "p2",
			"color": "#1f77b4",
			"label": "B",
			"style": "closed"
		},
		{
			"x": -4,
			"y": 9,
			"id": "p3",
			"color": "#1f77b4",
			"label": "C",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"p1",
				"p2",
				"p3"
			],
			"fillColor": "#11accd33",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc9187daacca72603
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: triangle_choice_b
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -9,
			"y": 4,
			"id": "q1",
			"color": "#e45756",
			"label": "A",
			"style": "closed"
		},
		{
			"x": -9,
			"y": 9,
			"id": "q2",
			"color": "#e45756",
			"label": "B",
			"style": "closed"
		},
		{
			"x": -4,
			"y": 9,
			"id": "q3",
			"color": "#e45756",
			"label": "C",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"q1",
				"q2",
				"q3"
			],
			"fillColor": "#e4575633",
			"strokeColor": "#e45756"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc9187daacca72603
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: triangle_choice_c
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -9,
			"y": 4,
			"id": "r1",
			"color": "#4caf50",
			"label": "A",
			"style": "closed"
		},
		{
			"x": -9,
			"y": 7,
			"id": "r2",
			"color": "#4caf50",
			"label": "B",
			"style": "closed"
		},
		{
			"x": -4,
			"y": -9,
			"id": "r3",
			"color": "#4caf50",
			"label": "C",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"r1",
				"r2",
				"r3"
			],
			"fillColor": "#4caf5033",
			"strokeColor": "#4caf50"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2e255b756911f229
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: coordinate_plane_initial
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x153dcbdb24bf96bf
// Course: 6th grade math
// Exercise: Drawing polygons with coordinates
// Widget key: coordinate_plane_initial
test("coordinate-plane - Drawing polygons with coordinates", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc3cf32285979342e
// Course: 6th grade math
// Exercise: Area and perimeter on the coordinate plane
// Widget key: graph_choice_a
test("coordinate-plane - Area and perimeter on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 340,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [
		{
			"x": -5,
			"y": 6,
			"id": "p1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 6,
			"id": "p2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 1,
			"id": "p3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -5,
			"y": 1,
			"id": "p4",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"p1",
				"p2",
				"p3",
				"p4"
			],
			"fillColor": "#00000000",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc3cf32285979342e
// Course: 6th grade math
// Exercise: Area and perimeter on the coordinate plane
// Widget key: graph_choice_b
test("coordinate-plane - Area and perimeter on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 340,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [
		{
			"x": -5,
			"y": 6,
			"id": "pt_left_top",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 6,
			"id": "pt_right_top",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [
		{
			"id": "top_segment",
			"color": "#11accd",
			"style": "solid",
			"points": [
				{
					"x": -5,
					"y": 6
				},
				{
					"x": -2,
					"y": 6
				}
			]
		}
	],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc3cf32285979342e
// Course: 6th grade math
// Exercise: Area and perimeter on the coordinate plane
// Widget key: graph_choice_c
test("coordinate-plane - Area and perimeter on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 340,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [
		{
			"x": -5,
			"y": 6,
			"id": "c_left_top",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 6,
			"id": "c_right_top",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc3cf32285979342e
// Course: 6th grade math
// Exercise: Area and perimeter on the coordinate plane
// Widget key: rectangle_points_image
test("coordinate-plane - Area and perimeter on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 340,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [
		{
			"x": -5,
			"y": 6,
			"id": "p_left_top",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 6,
			"id": "p_right_top",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc0cdf19d2b5cb0f3
// Course: 6th grade math
// Exercise: Area and perimeter on the coordinate plane
// Widget key: graph_choice_a
test("coordinate-plane - Area and perimeter on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 340,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [
		{
			"x": -4,
			"y": 4,
			"id": "A",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 4,
			"y": 4,
			"id": "B",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 4,
			"y": 3,
			"id": "C",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -4,
			"y": 3,
			"id": "D",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"A",
				"B",
				"C",
				"D"
			],
			"fillColor": "#11accd1A",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc0cdf19d2b5cb0f3
// Course: 6th grade math
// Exercise: Area and perimeter on the coordinate plane
// Widget key: graph_choice_b
test("coordinate-plane - Area and perimeter on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 340,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [
		{
			"x": -4,
			"y": 4,
			"id": "A",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 4,
			"y": 4,
			"id": "B",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 4,
			"y": 2,
			"id": "C",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -4,
			"y": 2,
			"id": "D",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"A",
				"B",
				"C",
				"D"
			],
			"fillColor": "#11accd1A",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc0cdf19d2b5cb0f3
// Course: 6th grade math
// Exercise: Area and perimeter on the coordinate plane
// Widget key: graph_choice_c
test("coordinate-plane - Area and perimeter on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 340,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [
		{
			"x": -2,
			"y": 4,
			"id": "A",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 2,
			"y": 4,
			"id": "B",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 2,
			"y": 2,
			"id": "C",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 2,
			"id": "D",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"A",
				"B",
				"C",
				"D"
			],
			"fillColor": "#11accd1A",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc0cdf19d2b5cb0f3
// Course: 6th grade math
// Exercise: Area and perimeter on the coordinate plane
// Widget key: coordinate_plane_points
test("coordinate-plane - Area and perimeter on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 340,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 325,
	"points": [
		{
			"x": -4,
			"y": 4,
			"id": "P_left_top",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 4,
			"y": 4,
			"id": "P_right_top",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xa308e4407932fbb6
// Course: 6th grade math
// Exercise: Quadrilateral problems on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrilateral problems on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -7,
			"y": -2,
			"id": "p1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 3,
			"y": -2,
			"id": "p2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 3,
			"y": -5,
			"id": "p3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -7,
			"y": -5,
			"id": "p4",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"p1",
				"p2",
				"p3",
				"p4"
			],
			"fillColor": "#00000000",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2130231f278cf3dc
// Course: 6th grade math
// Exercise: Quadrilateral problems on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrilateral problems on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 223,
	"xAxis": {
		"max": 5,
		"min": -4,
		"label": "x",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 6,
		"min": -3,
		"label": "y",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 270,
	"points": [
		{
			"x": -2,
			"y": -1,
			"id": "A",
			"color": "#000000",
			"label": "(-2, -1)",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 5,
			"id": "B",
			"color": "#000000",
			"label": "(c, 5)",
			"style": "closed"
		},
		{
			"x": 3,
			"y": 5,
			"id": "C",
			"color": "#000000",
			"label": "(3, 5)",
			"style": "closed"
		},
		{
			"x": 3,
			"y": -1,
			"id": "D",
			"color": "#000000",
			"label": "(3, d)",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"A",
				"B",
				"C",
				"D"
			],
			"fillColor": "#00000000",
			"strokeColor": "#000000"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xbf1cc072e328b0fa
// Course: 6th grade math
// Exercise: Quadrilateral problems on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrilateral problems on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": false
	},
	"height": 425,
	"points": [
		{
			"x": 4,
			"y": -7,
			"id": "pA",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 8,
			"y": -7,
			"id": "pB",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": 8,
			"y": -3,
			"id": "pC",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [
		{
			"id": "segment-AB",
			"color": "#11accd",
			"style": "solid",
			"points": [
				{
					"x": 4,
					"y": -7
				},
				{
					"x": 8,
					"y": -7
				}
			]
		},
		{
			"id": "segment-BC",
			"color": "#11accd",
			"style": "solid",
			"points": [
				{
					"x": 8,
					"y": -7
				},
				{
					"x": 8,
					"y": -3
				}
			]
		}
	],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x279ee4b02f62bd70
// Course: 6th grade math
// Exercise: Quadrilateral problems on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrilateral problems on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -7,
			"y": -7.5,
			"id": "p1",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": -7.5,
			"id": "p2",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -3,
			"y": 2.5,
			"id": "p3",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -7,
			"y": 2.5,
			"id": "p4",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [
		{
			"label": "",
			"isClosed": true,
			"vertices": [
				"p1",
				"p2",
				"p3",
				"p4"
			],
			"fillColor": "#00000000",
			"strokeColor": "#11accd"
		}
	],
	"distances": [],
	"polylines": [],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2dc3412b82f69a2f
// Course: 6th grade math
// Exercise: Quadrilateral problems on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrilateral problems on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": -5,
			"y": -8,
			"id": "A",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -5,
			"y": 0,
			"id": "B",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		},
		{
			"x": -2,
			"y": 0,
			"id": "C",
			"color": "#11accd",
			"label": "",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [
		{
			"id": "ab-segment",
			"color": "#11accd",
			"style": "solid",
			"points": [
				{
					"x": -5,
					"y": -8
				},
				{
					"x": -5,
					"y": 0
				}
			]
		},
		{
			"id": "bc-segment",
			"color": "#11accd",
			"style": "solid",
			"points": [
				{
					"x": -5,
					"y": 0
				},
				{
					"x": -2,
					"y": 0
				}
			]
		}
	],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xd7436c6190b8008c
// Course: 6th grade math
// Exercise: Quadrilateral problems on the coordinate plane
// Widget key: image_1
test("coordinate-plane - Quadrilateral problems on the coordinate plane", async () => {
	const input = {
	"lines": [],
	"width": 425,
	"xAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"yAxis": {
		"max": 10,
		"min": -10,
		"label": "",
		"tickInterval": 1,
		"showGridLines": true
	},
	"height": 425,
	"points": [
		{
			"x": 3,
			"y": 5,
			"id": "A",
			"color": "#11accd",
			"label": "A",
			"style": "closed"
		},
		{
			"x": 3,
			"y": -4,
			"id": "B",
			"color": "#11accd",
			"label": "B",
			"style": "closed"
		},
		{
			"x": -2,
			"y": -4,
			"id": "C",
			"color": "#11accd",
			"label": "C",
			"style": "closed"
		}
	],
	"polygons": [],
	"distances": [],
	"polylines": [
		{
			"id": "segment-AB",
			"color": "#11accd",
			"style": "solid",
			"points": [
				{
					"x": 3,
					"y": 5
				},
				{
					"x": 3,
					"y": -4
				}
			]
		},
		{
			"id": "segment-BC",
			"color": "#11accd",
			"style": "solid",
			"points": [
				{
					"x": 3,
					"y": -4
				},
				{
					"x": -2,
					"y": -4
				}
			]
		}
	],
	"showQuadrantLabels": false,
	"type": "coordinatePlane"
} satisfies CoordinatePlaneInput

	// Validate the input
	const parseResult = CoordinatePlaneComprehensivePropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted coordinatePlane:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateCoordinatePlane(parseResult.data)
	expect(svg).toMatchSnapshot()
})

