// ============================================================================
// EXTRACTED TEST FILE - AUTO-GENERATED
// ============================================================================
// This file was automatically generated from database structured_json data
// Generated on: 2025-09-18T05:17:02.169Z
// Widget Type: nPolygon
// Source: Real questions from database
//
// These tests use actual widget configurations extracted from production data
// to ensure comprehensive test coverage with realistic scenarios.
//
// Note: Database data may not perfectly match current widget schemas, so these
// tests rely on runtime validation within generateWidget() for flexibility.
//
// DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten on regeneration
//
// Run tests: bun test tests/widgets/n-polygon.extracted.test.ts
// Update snapshots: bun test tests/widgets/n-polygon.extracted.test.ts --update-snapshots
// ============================================================================

import { describe, test, expect } from "bun:test"
import { generateWidget } from "@superbuilders/qti-assessment-item-generator/widgets/widget-generator"
import type { Widget, WidgetInput } from "@superbuilders/qti-assessment-item-generator/widgets/registry"
import * as errors from "@superbuilders/errors"
import * as logger from "@superbuilders/slog"

describe("nPolygon widget tests", () => {
	// Extracted from question: x2130231f278cf3dc
	// Question: Which coordinate is greater?
	// Widget key: image_1
	test("n-polygon - [x2130231f278cf3dc] Which coordinate is greater?", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 400,
		  "height": 300,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x2ea82a3291511b2e
	// Question: Identify a solid from a vertical slice
	// Widget key: stimulus_shape
	test("n-polygon - [x2ea82a3291511b2e] Identify a solid from a vertical slice", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 340,
		  "height": 440,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xddab61063efd799b
	// Question: Vertical cross-section of a square pyramid
	// Widget key: choice_a_shape
	test("n-polygon - [xddab61063efd799b] Vertical cross-section of a square pyramid (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 300,
		  "height": 300,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xddab61063efd799b
	// Question: Vertical cross-section of a square pyramid
	// Widget key: choice_b_shape
	test("n-polygon - [xddab61063efd799b] Vertical cross-section of a square pyramid (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 300,
		  "height": 300,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xddab61063efd799b
	// Question: Vertical cross-section of a square pyramid
	// Widget key: choice_c_shape
	test("n-polygon - [xddab61063efd799b] Vertical cross-section of a square pyramid (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 300,
		  "height": 300,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xddab61063efd799b
	// Question: Vertical cross-section of a square pyramid
	// Widget key: choice_d_shape
	test("n-polygon - [xddab61063efd799b] Vertical cross-section of a square pyramid (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "hexagon",
		  "width": 300,
		  "height": 300,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x4139736ff42aefd2
	// Question: Identify the shape of a vertical cross-section
	// Widget key: choice_a_shape
	test("n-polygon - [x4139736ff42aefd2] Identify the shape of a vertical cross-section (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x4139736ff42aefd2
	// Question: Identify the shape of a vertical cross-section
	// Widget key: choice_c_shape
	test("n-polygon - [x4139736ff42aefd2] Identify the shape of a vertical cross-section (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 400,
		  "height": 300,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x4139736ff42aefd2
	// Question: Identify the shape of a vertical cross-section
	// Widget key: choice_d_shape
	test("n-polygon - [x4139736ff42aefd2] Identify the shape of a vertical cross-section (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x8bf3dcc1812f07b6
	// Question: Identify a solid from a horizontal slice (pentagon)
	// Widget key: image_1
	test("n-polygon - [x8bf3dcc1812f07b6] Identify a solid from a horizontal slice (pentagon)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "pentagon",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#f2f2f2"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x209d34a33212eb67
	// Question: Identify the solid from a triangular horizontal slice
	// Widget key: triangle_image
	test("n-polygon - [x209d34a33212eb67] Identify the solid from a triangular horizontal slice", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xb0b26af2552ebf85
	// Question: Select a solid that produces a triangular vertical slice
	// Widget key: stimulus_triangle
	test("n-polygon - [xb0b26af2552ebf85] Select a solid that produces a triangular vertical slice", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x4f1f8eb1e5cd00ec
	// Question: Identify a solid from its horizontal cross-section
	// Widget key: stimulus_hexagon
	test("n-polygon - [x4f1f8eb1e5cd00ec] Identify a solid from its horizontal cross-section", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "hexagon",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa63d03bcdc40499a
	// Question: Identify a solid from a square cross-section
	// Widget key: stimulus_shape
	test("n-polygon - [xa63d03bcdc40499a] Identify a solid from a square cross-section", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x7b7f9e81dc7e0cea
	// Question: Cross-section of a pentagonal prism by a horizontal plane
	// Widget key: choice_a_shape
	test("n-polygon - [x7b7f9e81dc7e0cea] Cross-section of a pentagonal prism by a horizontal plane (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "pentagon",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x7b7f9e81dc7e0cea
	// Question: Cross-section of a pentagonal prism by a horizontal plane
	// Widget key: choice_b_shape
	test("n-polygon - [x7b7f9e81dc7e0cea] Cross-section of a pentagonal prism by a horizontal plane (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x7b7f9e81dc7e0cea
	// Question: Cross-section of a pentagonal prism by a horizontal plane
	// Widget key: choice_c_shape
	test("n-polygon - [x7b7f9e81dc7e0cea] Cross-section of a pentagonal prism by a horizontal plane (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 400,
		  "height": 300,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x7b7f9e81dc7e0cea
	// Question: Cross-section of a pentagonal prism by a horizontal plane
	// Widget key: choice_d_shape
	test("n-polygon - [x7b7f9e81dc7e0cea] Cross-section of a pentagonal prism by a horizontal plane (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x7c120e3f24093a5b
	// Question: Identify the cross-section of a triangular prism
	// Widget key: choice_a_shape
	test("n-polygon - [x7c120e3f24093a5b] Identify the cross-section of a triangular prism (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x7c120e3f24093a5b
	// Question: Identify the cross-section of a triangular prism
	// Widget key: choice_b_shape
	test("n-polygon - [x7c120e3f24093a5b] Identify the cross-section of a triangular prism (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x7c120e3f24093a5b
	// Question: Identify the cross-section of a triangular prism
	// Widget key: choice_c_shape
	test("n-polygon - [x7c120e3f24093a5b] Identify the cross-section of a triangular prism (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x72bb801397b54d5e
	// Question: Identify the cross-section of a square-based pyramid
	// Widget key: choice_a_shape
	test("n-polygon - [x72bb801397b54d5e] Identify the cross-section of a square-based pyramid (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 340,
		  "height": 340,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x72bb801397b54d5e
	// Question: Identify the cross-section of a square-based pyramid
	// Widget key: choice_b_shape
	test("n-polygon - [x72bb801397b54d5e] Identify the cross-section of a square-based pyramid (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 340,
		  "height": 340,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x72bb801397b54d5e
	// Question: Identify the cross-section of a square-based pyramid
	// Widget key: choice_c_shape
	test("n-polygon - [x72bb801397b54d5e] Identify the cross-section of a square-based pyramid (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 360,
		  "height": 300,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x72bb801397b54d5e
	// Question: Identify the cross-section of a square-based pyramid
	// Widget key: choice_d_shape
	test("n-polygon - [x72bb801397b54d5e] Identify the cross-section of a square-based pyramid (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "pentagon",
		  "width": 340,
		  "height": 340,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x80dc1341b9007790
	// Question: Identify the horizontal cross-section of a right prism
	// Widget key: choice_a_shape
	test("n-polygon - [x80dc1341b9007790] Identify the horizontal cross-section of a right prism (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x80dc1341b9007790
	// Question: Identify the horizontal cross-section of a right prism
	// Widget key: choice_b_shape
	test("n-polygon - [x80dc1341b9007790] Identify the horizontal cross-section of a right prism (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x80dc1341b9007790
	// Question: Identify the horizontal cross-section of a right prism
	// Widget key: choice_c_shape
	test("n-polygon - [x80dc1341b9007790] Identify the horizontal cross-section of a right prism (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 400,
		  "height": 300,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x80dc1341b9007790
	// Question: Identify the horizontal cross-section of a right prism
	// Widget key: choice_d_shape
	test("n-polygon - [x80dc1341b9007790] Identify the horizontal cross-section of a right prism (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "octagon",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc8ec7679f407c09d
	// Question: Identify the horizontal cross-section of a triangular prism
	// Widget key: choice_a_shape
	test("n-polygon - [xc8ec7679f407c09d] Identify the horizontal cross-section of a triangular prism (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 300,
		  "height": 300,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc8ec7679f407c09d
	// Question: Identify the horizontal cross-section of a triangular prism
	// Widget key: choice_b_shape
	test("n-polygon - [xc8ec7679f407c09d] Identify the horizontal cross-section of a triangular prism (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 300,
		  "height": 300,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc8ec7679f407c09d
	// Question: Identify the horizontal cross-section of a triangular prism
	// Widget key: choice_c_shape
	test("n-polygon - [xc8ec7679f407c09d] Identify the horizontal cross-section of a triangular prism (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 300,
		  "height": 300,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc8ec7679f407c09d
	// Question: Identify the horizontal cross-section of a triangular prism
	// Widget key: choice_d_shape
	test("n-polygon - [xc8ec7679f407c09d] Identify the horizontal cross-section of a triangular prism (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "octagon",
		  "width": 300,
		  "height": 300,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa33f179a801021da
	// Question: Cross-section of a right rectangular prism by a vertical plane
	// Widget key: choice_a_visual
	test("n-polygon - [xa33f179a801021da] Cross-section of a right rectangular prism by a vertical plane (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 400,
		  "height": 300,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa33f179a801021da
	// Question: Cross-section of a right rectangular prism by a vertical plane
	// Widget key: choice_b_visual
	test("n-polygon - [xa33f179a801021da] Cross-section of a right rectangular prism by a vertical plane (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 340,
		  "height": 340,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa33f179a801021da
	// Question: Cross-section of a right rectangular prism by a vertical plane
	// Widget key: choice_c_visual
	test("n-polygon - [xa33f179a801021da] Cross-section of a right rectangular prism by a vertical plane (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "octagon",
		  "width": 340,
		  "height": 340,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa33f179a801021da
	// Question: Cross-section of a right rectangular prism by a vertical plane
	// Widget key: choice_d_visual
	test("n-polygon - [xa33f179a801021da] Cross-section of a right rectangular prism by a vertical plane (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 340,
		  "height": 340,
		  "fillColor": "#ffffff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xaaf221c1e7ea291e
	// Question: Identify the shape of a horizontal cross-section of a square pyramid
	// Widget key: choice_a_shape
	test("n-polygon - [xaaf221c1e7ea291e] Identify the shape of a horizontal cross-section of a square pyramid (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xaaf221c1e7ea291e
	// Question: Identify the shape of a horizontal cross-section of a square pyramid
	// Widget key: choice_b_shape
	test("n-polygon - [xaaf221c1e7ea291e] Identify the shape of a horizontal cross-section of a square pyramid (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xaaf221c1e7ea291e
	// Question: Identify the shape of a horizontal cross-section of a square pyramid
	// Widget key: choice_c_shape
	test("n-polygon - [xaaf221c1e7ea291e] Identify the shape of a horizontal cross-section of a square pyramid (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xaaf221c1e7ea291e
	// Question: Identify the shape of a horizontal cross-section of a square pyramid
	// Widget key: choice_d_shape
	test("n-polygon - [xaaf221c1e7ea291e] Identify the shape of a horizontal cross-section of a square pyramid (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "pentagon",
		  "width": 320,
		  "height": 320,
		  "fillColor": "#FFFFFF"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa20e5503075f43b9
	// Question: Select the scaled rectangle for the mausoleum plan
	// Widget key: rect_choice_a
	test("n-polygon - [xa20e5503075f43b9] Select the scaled rectangle for the mausoleum plan (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 360,
		  "height": 300,
		  "fillColor": "#FDE68A"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa20e5503075f43b9
	// Question: Select the scaled rectangle for the mausoleum plan
	// Widget key: rect_choice_b
	test("n-polygon - [xa20e5503075f43b9] Select the scaled rectangle for the mausoleum plan (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 360,
		  "height": 300,
		  "fillColor": "#A7F3D0"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa20e5503075f43b9
	// Question: Select the scaled rectangle for the mausoleum plan
	// Widget key: rect_choice_c
	test("n-polygon - [xa20e5503075f43b9] Select the scaled rectangle for the mausoleum plan (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "hexagon",
		  "width": 360,
		  "height": 300,
		  "fillColor": "#BFDBFE"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x63d0f3e2dac95aee
	// Question: Draw a scaled square face of a salt crystal
	// Widget key: square_face_choice_a
	test("n-polygon - [x63d0f3e2dac95aee] Draw a scaled square face of a salt crystal (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 400,
		  "height": 400,
		  "fillColor": "#a7c7ff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x63d0f3e2dac95aee
	// Question: Draw a scaled square face of a salt crystal
	// Widget key: square_face_choice_b
	test("n-polygon - [x63d0f3e2dac95aee] Draw a scaled square face of a salt crystal (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 400,
		  "height": 400,
		  "fillColor": "#a7c7ff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x63d0f3e2dac95aee
	// Question: Draw a scaled square face of a salt crystal
	// Widget key: square_face_choice_c
	test("n-polygon - [x63d0f3e2dac95aee] Draw a scaled square face of a salt crystal (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "pentagon",
		  "width": 400,
		  "height": 400,
		  "fillColor": "#a7c7ff"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xb33fd58db9a5f93e
	// Question: Select a rectangle representing the manor's base
	// Widget key: rectangle_choice_a
	test("n-polygon - [xb33fd58db9a5f93e] Select a rectangle representing the manor's base (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "square",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#88CCEE"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xb33fd58db9a5f93e
	// Question: Select a rectangle representing the manor's base
	// Widget key: rectangle_choice_b
	test("n-polygon - [xb33fd58db9a5f93e] Select a rectangle representing the manor's base (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#66CC99"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xb33fd58db9a5f93e
	// Question: Select a rectangle representing the manor's base
	// Widget key: rectangle_choice_c
	test("n-polygon - [xb33fd58db9a5f93e] Select a rectangle representing the manor's base (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "pentagon",
		  "width": 360,
		  "height": 360,
		  "fillColor": "#EE8866"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc3cf32285979342e
	// Question: Identify a rectangle from two vertices and the perimeter
	// Widget key: rectangle_choice_a
	test("n-polygon - [xc3cf32285979342e] Identify a rectangle from two vertices and the perimeter (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "triangle",
		  "width": 340,
		  "height": 455,
		  "fillColor": "#E6E6E6"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc3cf32285979342e
	// Question: Identify a rectangle from two vertices and the perimeter
	// Widget key: rectangle_choice_b
	test("n-polygon - [xc3cf32285979342e] Identify a rectangle from two vertices and the perimeter (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "rectangle",
		  "width": 340,
		  "height": 455,
		  "fillColor": "#E6E6E6"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc3cf32285979342e
	// Question: Identify a rectangle from two vertices and the perimeter
	// Widget key: rectangle_choice_c
	test("n-polygon - [xc3cf32285979342e] Identify a rectangle from two vertices and the perimeter (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "nPolygon",
		  "shape": "pentagon",
		  "width": 340,
		  "height": 455,
		  "fillColor": "#E6E6E6"
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for nPolygon", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

})
