// ============================================================================
// EXTRACTED TEST FILE - AUTO-GENERATED
// ============================================================================
// This file was automatically generated from database structured_json data
// Generated on: 2025-09-01T22:27:08.781Z
// Widget Type: numberLineWithAction
// Source: Real questions from database
//
// These tests use actual widget configurations extracted from production data
// to ensure comprehensive test coverage with realistic scenarios.
//
// DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten on regeneration
//
// Run tests: bun test tests/widgets/number-line-with-action.extracted.test.ts
// Update snapshots: bun test tests/widgets/number-line-with-action.extracted.test.ts --update-snapshots
// ============================================================================

import { expect, test } from "bun:test"
import type { z } from "zod"
import { generateNumberLineWithAction, NumberLineWithActionPropsSchema } from "@/lib/widgets/generators"

type NumberLineWithActionInput = z.input<typeof NumberLineWithActionPropsSchema>


// Extracted from question: x7362559be7b98f2d
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -12,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": -2,
			"label": ""
		},
		{
			"delta": -7,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x7362559be7b98f2d
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -12,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": -5,
			"label": ""
		},
		{
			"delta": -4,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x7362559be7b98f2d
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -12,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": 2,
			"label": ""
		},
		{
			"delta": -7,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc87663abd3f6b59d
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_a
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 11,
	"min": -4,
	"width": 440,
	"height": 150,
	"actions": [
		{
			"delta": 3.5,
			"label": ""
		},
		{
			"delta": -6,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc87663abd3f6b59d
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_b
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 11,
	"min": -4,
	"width": 440,
	"height": 150,
	"actions": [
		{
			"delta": 6,
			"label": ""
		},
		{
			"delta": -3.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xc87663abd3f6b59d
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_c
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 11,
	"min": -4,
	"width": 440,
	"height": 150,
	"actions": [
		{
			"delta": 3.5,
			"label": ""
		},
		{
			"delta": 6.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xa5da05cd450e06fe
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -2,
			"label": ""
		},
		{
			"delta": 4.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [
		{
			"text": "-9",
			"value": -9
		},
		{
			"text": "-6",
			"value": -6
		},
		{
			"text": "-3",
			"value": -3
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "3",
			"value": 3
		}
	],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xa5da05cd450e06fe
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": 2,
			"label": ""
		},
		{
			"delta": -4.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [
		{
			"text": "-9",
			"value": -9
		},
		{
			"text": "-6",
			"value": -6
		},
		{
			"text": "-3",
			"value": -3
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "3",
			"value": 3
		}
	],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xa5da05cd450e06fe
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -2,
			"label": ""
		},
		{
			"delta": -4.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [
		{
			"text": "-9",
			"value": -9
		},
		{
			"text": "-6",
			"value": -6
		},
		{
			"text": "-3",
			"value": -3
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "3",
			"value": 3
		}
	],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xb3accc11204a02de
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_a
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -5,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": 6,
			"label": "6"
		},
		{
			"delta": -2,
			"label": "(-2)"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xb3accc11204a02de
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_b
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -5,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": 4,
			"label": "4"
		},
		{
			"delta": 2,
			"label": "2"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xb3accc11204a02de
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_c
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -5,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": 6,
			"label": "6"
		},
		{
			"delta": 2,
			"label": "2"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xd5c63f0c55b119ef
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_model
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -9,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": 5.5,
			"label": ""
		},
		{
			"delta": -3,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xd5c63f0c55b119ef
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_model
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -9,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": -5.5,
			"label": ""
		},
		{
			"delta": 3,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xd5c63f0c55b119ef
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_model
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -9,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": -5.5,
			"label": ""
		},
		{
			"delta": -3,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xf6faf90e920bece0
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -5,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -5,
			"label": "-5"
		},
		{
			"delta": 2.5,
			"label": "+2.5"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xf6faf90e920bece0
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -5,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": 5,
			"label": "+5"
		},
		{
			"delta": 2.5,
			"label": "+2.5"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xf6faf90e920bece0
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -5,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": 5,
			"label": "+5"
		},
		{
			"delta": 2.5,
			"label": "+2.5"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x82261bcc5edaa00e
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_a
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -2.5,
			"label": "-2 1/2"
		},
		{
			"delta": -5,
			"label": "+(-5)"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x82261bcc5edaa00e
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_b
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -2.5,
			"label": "-2 1/2"
		},
		{
			"delta": 5,
			"label": "+5"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x82261bcc5edaa00e
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_c
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": 2.5,
			"label": "+2 1/2"
		},
		{
			"delta": -5,
			"label": "-5"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0201659c2893f524
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_a
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 120,
	"actions": [
		{
			"delta": -0.6666666666666666,
			"label": "-2/3"
		},
		{
			"delta": -0.3333333333333333,
			"label": "+(-1/3)"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 0.3333333333333333,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0201659c2893f524
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_b
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 120,
	"actions": [
		{
			"delta": -0.6666666666666666,
			"label": "-2/3"
		},
		{
			"delta": 0.3333333333333333,
			"label": "+1/3"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 0.3333333333333333,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0201659c2893f524
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_c
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 120,
	"actions": [
		{
			"delta": 0.6666666666666666,
			"label": "+2/3"
		},
		{
			"delta": 0.3333333333333333,
			"label": "+1/3"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 0.3333333333333333,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x44abd870dc49e748
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_image
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -3,
	"width": 105,
	"height": 240,
	"actions": [
		{
			"delta": -1.5,
			"label": ""
		},
		{
			"delta": 1.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [
		{
			"text": "-3",
			"value": -3
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "3",
			"value": 3
		}
	],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x44abd870dc49e748
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_image
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -3,
	"width": 105,
	"height": 240,
	"actions": [
		{
			"delta": -1.5,
			"label": ""
		},
		{
			"delta": -1.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [
		{
			"text": "-3",
			"value": -3
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "3",
			"value": 3
		}
	],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x44abd870dc49e748
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_image
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -3,
	"width": 105,
	"height": 240,
	"actions": [
		{
			"delta": 1.5,
			"label": ""
		},
		{
			"delta": 1.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [
		{
			"text": "-3",
			"value": -3
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "3",
			"value": 3
		}
	],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x293c0f0461f4d484
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_a
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -4.5,
			"label": ""
		},
		{
			"delta": -3.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 3,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x293c0f0461f4d484
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_b
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -2.5,
			"label": ""
		},
		{
			"delta": -2,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 3,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x293c0f0461f4d484
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_c
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -4.5,
			"label": ""
		},
		{
			"delta": 3.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 3,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x53fb22deb1bc7f3e
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_a
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -8,
	"width": 460,
	"height": 132,
	"actions": [
		{
			"delta": 2.5,
			"label": "+2.5"
		},
		{
			"delta": 4.5,
			"label": "+4.5"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x53fb22deb1bc7f3e
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_b
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -8,
	"width": 460,
	"height": 132,
	"actions": [
		{
			"delta": -2.5,
			"label": "-2.5"
		},
		{
			"delta": 4.5,
			"label": "+4.5"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x53fb22deb1bc7f3e
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_c
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 8,
	"min": -8,
	"width": 460,
	"height": 132,
	"actions": [
		{
			"delta": 1.5,
			"label": "+1.5"
		},
		{
			"delta": 2.5,
			"label": "+2.5"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x21aa7b20592b802a
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 6,
	"min": -9,
	"width": 460,
	"height": 112.5531914893617,
	"actions": [
		{
			"delta": -2,
			"label": ""
		},
		{
			"delta": -3.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x21aa7b20592b802a
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 6,
	"min": -9,
	"width": 460,
	"height": 112.5531914893617,
	"actions": [
		{
			"delta": -2,
			"label": ""
		},
		{
			"delta": 3.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x21aa7b20592b802a
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 6,
	"min": -9,
	"width": 460,
	"height": 112.5531914893617,
	"actions": [
		{
			"delta": 2,
			"label": ""
		},
		{
			"delta": -3.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x9f41a9112f828675
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 4,
	"min": -4,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": 1.5,
			"label": "+1.5"
		},
		{
			"delta": -4,
			"label": "(-4)"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x9f41a9112f828675
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 4,
	"min": -4,
	"width": 162,
	"height": 240,
	"actions": [
		{
			"delta": -1.5,
			"label": "-1.5"
		},
		{
			"delta": 4,
			"label": "+4"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x9f41a9112f828675
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 4,
	"min": -4,
	"width": 138,
	"height": 240,
	"actions": [
		{
			"delta": -1.5,
			"label": "-1.5"
		},
		{
			"delta": -1,
			"label": "-1"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x621482e0914d615c
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: nl_choice_a
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 6,
	"min": -6,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": 2.5,
			"label": ""
		},
		{
			"delta": 3,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 2,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x621482e0914d615c
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: nl_choice_b
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 6,
	"min": -6,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -2.5,
			"label": ""
		},
		{
			"delta": -3,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 2,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x621482e0914d615c
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: nl_choice_c
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 6,
	"min": -6,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -2.5,
			"label": ""
		},
		{
			"delta": 3,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 2,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x5381f9d9641ca379
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 6,
	"min": -9,
	"width": 460,
	"height": 112.5531914893617,
	"actions": [
		{
			"delta": -4,
			"label": ""
		},
		{
			"delta": 7.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x5381f9d9641ca379
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 6,
	"min": -9,
	"width": 460,
	"height": 112.5531914893617,
	"actions": [
		{
			"delta": 4,
			"label": ""
		},
		{
			"delta": -7.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x5381f9d9641ca379
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 6,
	"min": -9,
	"width": 460,
	"height": 112.5531914893617,
	"actions": [
		{
			"delta": -2,
			"label": ""
		},
		{
			"delta": 5.5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xd71c42100bcc7400
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 130,
	"actions": [
		{
			"delta": 0.75,
			"label": ""
		},
		{
			"delta": -0.25,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [
		{
			"text": "-1",
			"value": -1
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "1",
			"value": 1
		}
	],
	"tickInterval": 0.25,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xd71c42100bcc7400
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 130,
	"actions": [
		{
			"delta": -0.75,
			"label": ""
		},
		{
			"delta": -0.25,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [
		{
			"text": "-1",
			"value": -1
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "1",
			"value": 1
		}
	],
	"tickInterval": 0.25,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xd71c42100bcc7400
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 130,
	"actions": [
		{
			"delta": -0.75,
			"label": ""
		},
		{
			"delta": 0.25,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [
		{
			"text": "-1",
			"value": -1
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "1",
			"value": 1
		}
	],
	"tickInterval": 0.25,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x90c8983e96809916
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_a
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 120,
	"actions": [
		{
			"delta": -0.5,
			"label": ""
		},
		{
			"delta": 1.25,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [
		{
			"text": "-1",
			"value": -1
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "1",
			"value": 1
		}
	],
	"tickInterval": 0.25,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x90c8983e96809916
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_b
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 120,
	"actions": [
		{
			"delta": 0.5,
			"label": ""
		},
		{
			"delta": -1.25,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [
		{
			"text": "-1",
			"value": -1
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "1",
			"value": 1
		}
	],
	"tickInterval": 0.25,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x90c8983e96809916
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_c
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 120,
	"actions": [
		{
			"delta": 0.5,
			"label": ""
		},
		{
			"delta": -1.25,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [
		{
			"text": "-1",
			"value": -1
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "1",
			"value": 1
		}
	],
	"tickInterval": 0.25,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xced586698a4a059a
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_a
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 4,
	"min": -4,
	"width": 150,
	"height": 240,
	"actions": [
		{
			"delta": 3.5,
			"label": "+3.5"
		},
		{
			"delta": -5,
			"label": "(-5)"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 2,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xced586698a4a059a
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_b
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 4,
	"min": -4,
	"width": 150,
	"height": 240,
	"actions": [
		{
			"delta": -3.5,
			"label": "-3.5"
		},
		{
			"delta": 5,
			"label": "+5"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 2,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xced586698a4a059a
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: number_line_choice_c
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 4,
	"min": -4,
	"width": 150,
	"height": 240,
	"actions": [
		{
			"delta": -4,
			"label": "-4"
		},
		{
			"delta": 1.5,
			"label": "+1.5"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 2,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xcabd43499582d390
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 120,
	"actions": [
		{
			"delta": -0.4,
			"label": ""
		},
		{
			"delta": 0.8,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [
		{
			"text": "-1",
			"value": -1
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "1",
			"value": 1
		}
	],
	"tickInterval": 0.2,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xcabd43499582d390
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 150,
	"actions": [
		{
			"delta": -0.8,
			"label": ""
		},
		{
			"delta": 0.4,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [
		{
			"text": "-1",
			"value": -1
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "1",
			"value": 1
		}
	],
	"tickInterval": 0.2,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xcabd43499582d390
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_numberline
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 1,
	"min": -1,
	"width": 440,
	"height": 130,
	"actions": [
		{
			"delta": 0.4,
			"label": ""
		},
		{
			"delta": -0.8,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [
		{
			"text": "-1",
			"value": -1
		},
		{
			"text": "0",
			"value": 0
		},
		{
			"text": "1",
			"value": 1
		}
	],
	"tickInterval": 0.2,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x51dd8b7ef627dd5b
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_a_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -5,
			"label": "-5"
		},
		{
			"delta": -2.5,
			"label": "+(-2.5)"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x51dd8b7ef627dd5b
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_b_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -5,
			"label": "-5"
		},
		{
			"delta": 2.5,
			"label": "+2.5"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x51dd8b7ef627dd5b
// Course: 7th grade math
// Exercise: Adding negative numbers on the number line
// Widget key: choice_c_number_line
test("number-line-with-action - Adding negative numbers on the number line", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -2.5,
			"label": "-2.5"
		},
		{
			"delta": -5,
			"label": "-5"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xd610b87535fc620e
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 4,
	"min": -12,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": -3,
			"label": ""
		},
		{
			"delta": -3,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 4,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xf63af1f04fe534b3
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": -1,
			"label": ""
		},
		{
			"delta": -6,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 3,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xdab0ac9f3c04c60c
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 3,
	"min": -3,
	"width": 180,
	"height": 240,
	"actions": [
		{
			"delta": 2,
			"label": ""
		},
		{
			"delta": -4,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xf39cda2a86b64de2
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 3,
	"min": -6,
	"width": 158,
	"height": 240,
	"actions": [
		{
			"delta": 2,
			"label": ""
		},
		{
			"delta": -7,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xf8477be75aae4dbd
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 14,
	"min": -5,
	"width": 96,
	"height": 240,
	"actions": [
		{
			"delta": 5,
			"label": ""
		},
		{
			"delta": 9,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 5,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x9108c4694f368e4b
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 10,
	"min": 0,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": 5,
			"label": "+5"
		},
		{
			"delta": 2,
			"label": "+2"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x39cfc94b3d039302
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 20,
	"min": -20,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": -4,
			"label": "-4"
		},
		{
			"delta": -9,
			"label": "-9"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xae44b6995c503ad2
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 3,
	"min": -9,
	"width": 135,
	"height": 240,
	"actions": [
		{
			"delta": -3,
			"label": ""
		},
		{
			"delta": -5,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x71f64f609e0ecd93
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 6,
	"min": -6,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": 4,
			"label": "4"
		},
		{
			"delta": -6,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x78abb9f914c32982
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 10,
	"min": 0,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": 9,
			"label": "9"
		},
		{
			"delta": -3,
			"label": "-3"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x5e1e310fb9a0bb90
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 10,
	"min": -10,
	"width": 128,
	"height": 240,
	"actions": [
		{
			"delta": -2,
			"label": "-2"
		},
		{
			"delta": 9,
			"label": "+9"
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x9c5db293cf7cd413
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 6,
	"min": -6,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": -3,
			"label": "-3"
		},
		{
			"delta": 4,
			"label": "4"
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x9dde932a1383109d
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 12,
	"min": -12,
	"width": 127.05882352941177,
	"height": 240,
	"actions": [
		{
			"delta": -9,
			"label": ""
		},
		{
			"delta": -2,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x8eb6b54b62efd010
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 10,
	"min": 0,
	"width": 156.923,
	"height": 240,
	"actions": [
		{
			"delta": 5,
			"label": ""
		},
		{
			"delta": 2,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xf44c0185ceef49ea
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 4,
	"min": -8,
	"width": 460,
	"height": 113,
	"actions": [
		{
			"delta": -4,
			"label": ""
		},
		{
			"delta": -2,
			"label": ""
		}
	],
	"startValue": 0,
	"orientation": "horizontal",
	"customLabels": [],
	"tickInterval": 4,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x52861d81023728a9
// Course: 7th grade math
// Exercise: Number equations & number lines
// Widget key: image_1
test("number-line-with-action - Number equations number lines", async () => {
	const input = {
	"max": 12,
	"min": -12,
	"width": 120,
	"height": 240,
	"actions": [
		{
			"delta": -4,
			"label": " "
		},
		{
			"delta": -6,
			"label": " "
		}
	],
	"startValue": 0,
	"orientation": "vertical",
	"customLabels": [],
	"tickInterval": 1,
	"type": "numberLineWithAction"
} satisfies NumberLineWithActionInput

	// Validate the input
	const parseResult = NumberLineWithActionPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted numberLineWithAction:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = await generateNumberLineWithAction(parseResult.data)
	expect(svg).toMatchSnapshot()
})

