// ============================================================================
// EXTRACTED TEST FILE - AUTO-GENERATED
// ============================================================================
// This file was automatically generated from database structured_json data
// Generated on: 2025-09-01T22:43:40.171Z
// Widget Type: polyhedronNetDiagram
// Source: Real questions from database
//
// These tests use actual widget configurations extracted from production data
// to ensure comprehensive test coverage with realistic scenarios.
//
// DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten on regeneration
//
// Run tests: bun test tests/widgets/polyhedron-net-diagram.extracted.test.ts
// Update snapshots: bun test tests/widgets/polyhedron-net-diagram.extracted.test.ts --update-snapshots
// ============================================================================

import { expect, test } from "bun:test"
import type { z } from "zod"
import { generatePolyhedronNetDiagram, PolyhedronNetDiagramPropsSchema } from "@/lib/widgets/generators"

type PolyhedronNetDiagramInput = z.input<typeof PolyhedronNetDiagramPropsSchema>


// Extracted from question: xb8111de5396058b2
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_a
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"type": "rectangle",
		"width": 5,
		"length": 8
	},
	"width": 550,
	"height": 380,
	"showLabels": false,
	"lateralHeight": 6,
	"polyhedronType": "rectangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xb8111de5396058b2
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_b
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5.5,
		"side2": 6.5,
		"height": 5
	},
	"width": 420,
	"height": 380,
	"showLabels": false,
	"lateralHeight": 6,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xb8111de5396058b2
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_c
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 600,
	"height": 360,
	"showLabels": false,
	"lateralHeight": 8,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xb8111de5396058b2
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_d
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 4,
		"type": "pentagon"
	},
	"width": 520,
	"height": 520,
	"showLabels": false,
	"lateralHeight": 6.5,
	"polyhedronType": "pentagonalPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x8cd9cfce22606e6e
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_a
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 6,
		"type": "square"
	},
	"width": 480,
	"height": 420,
	"showLabels": false,
	"lateralHeight": 7,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x8cd9cfce22606e6e
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_b
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 6,
		"side2": 6,
		"height": 5.196
	},
	"width": 520,
	"height": 420,
	"showLabels": false,
	"lateralHeight": 5.8,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x8cd9cfce22606e6e
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_c
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 4,
		"type": "pentagon"
	},
	"width": 520,
	"height": 520,
	"showLabels": false,
	"lateralHeight": 6.5,
	"polyhedronType": "pentagonalPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x8cd9cfce22606e6e
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_d
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 520,
	"height": 380,
	"showLabels": false,
	"lateralHeight": 8,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x821446306d5d3745
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_a
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"type": "rectangle",
		"width": 4,
		"length": 8
	},
	"width": 520,
	"height": 340,
	"showLabels": false,
	"lateralHeight": 5,
	"polyhedronType": "rectangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x821446306d5d3745
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_b
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 4,
		"type": "triangle",
		"side1": 3,
		"side2": 5,
		"height": 3
	},
	"width": 460,
	"height": 380,
	"showLabels": false,
	"lateralHeight": 5,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x821446306d5d3745
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_c
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 7,
		"height": 4
	},
	"width": 460,
	"height": 380,
	"showLabels": false,
	"lateralHeight": 6,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x821446306d5d3745
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_d
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 4,
		"type": "triangle",
		"side1": 3,
		"side2": 5,
		"height": 3
	},
	"width": 520,
	"height": 360,
	"showLabels": false,
	"lateralHeight": 8,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2d009ffa46ca3820
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: image_1
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 1,
		"type": "square"
	},
	"width": 195,
	"height": 156,
	"showLabels": false,
	"polyhedronType": "cube",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x6a3fb181fd601eab
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: image_1
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 120,
	"height": 195,
	"showLabels": false,
	"lateralHeight": 8,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x033d85774a48004c
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: choice_a_net
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 4,
		"type": "square"
	},
	"width": 480,
	"height": 420,
	"showLabels": false,
	"lateralHeight": 5,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x033d85774a48004c
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: choice_b_net
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 4,
		"type": "triangle",
		"side1": 4.3,
		"side2": 4.3,
		"height": 3.5
	},
	"width": 460,
	"height": 380,
	"showLabels": false,
	"lateralHeight": 4,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x033d85774a48004c
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: choice_c_net
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 3.5,
		"type": "pentagon"
	},
	"width": 500,
	"height": 420,
	"showLabels": false,
	"lateralHeight": 4.5,
	"polyhedronType": "pentagonalPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x033d85774a48004c
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: choice_d_net
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 4.5,
		"type": "triangle",
		"side1": 4.2,
		"side2": 4.2,
		"height": 3.5
	},
	"width": 580,
	"height": 360,
	"showLabels": false,
	"lateralHeight": 6,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xe8a5aa515c090a6d
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_a
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 480,
	"height": 360,
	"showLabels": false,
	"lateralHeight": 8,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xe8a5aa515c090a6d
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_b
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 420,
	"height": 380,
	"showLabels": false,
	"lateralHeight": 6,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xe8a5aa515c090a6d
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_c
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 4,
		"type": "pentagon"
	},
	"width": 500,
	"height": 500,
	"showLabels": false,
	"lateralHeight": 6.5,
	"polyhedronType": "pentagonalPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xe8a5aa515c090a6d
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_d
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 5,
		"type": "square"
	},
	"width": 400,
	"height": 400,
	"showLabels": false,
	"polyhedronType": "cube",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x29a33987cc70cc98
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: image_1
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 5,
		"type": "square"
	},
	"width": 420,
	"height": 420,
	"showLabels": false,
	"lateralHeight": 6,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x4434040c275cad18
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: image_1
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 5
	},
	"width": 198,
	"height": 165,
	"showLabels": false,
	"lateralHeight": 6,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2aa7cbb873cb1a43
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_a
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 6,
		"type": "square"
	},
	"width": 420,
	"height": 420,
	"showLabels": false,
	"lateralHeight": 7,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2aa7cbb873cb1a43
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_b
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 420,
	"height": 360,
	"showLabels": false,
	"lateralHeight": 5,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2aa7cbb873cb1a43
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_c
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 5,
		"type": "triangle",
		"side1": 4.5,
		"side2": 4.5,
		"height": 4
	},
	"width": 420,
	"height": 360,
	"showLabels": false,
	"lateralHeight": 5,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2aa7cbb873cb1a43
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_d
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 500,
	"height": 350,
	"showLabels": false,
	"lateralHeight": 8,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x086f122f1f57f437
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: image_1
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 500,
	"height": 320,
	"showLabels": false,
	"lateralHeight": 8,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x81677ce01e6fdaad
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: image_1
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 500,
	"height": 350,
	"showLabels": false,
	"lateralHeight": 7,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x1b2d522be1ad518c
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: image_1
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 500,
	"height": 350,
	"showLabels": false,
	"lateralHeight": 10,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2b03516c0180b352
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: image_1
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 6,
		"type": "square"
	},
	"width": 420,
	"height": 420,
	"showLabels": false,
	"lateralHeight": 7,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x7b3cc9da2395d5f7
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_a
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"side": 6,
		"type": "square"
	},
	"width": 450,
	"height": 450,
	"showLabels": false,
	"lateralHeight": 7,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x7b3cc9da2395d5f7
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_b
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"type": "rectangle",
		"width": 6,
		"length": 10
	},
	"width": 550,
	"height": 350,
	"showLabels": false,
	"lateralHeight": 8,
	"polyhedronType": "rectangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x7b3cc9da2395d5f7
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_c
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 8,
		"type": "triangle",
		"side1": 6,
		"side2": 7,
		"height": 5
	},
	"width": 550,
	"height": 350,
	"showLabels": false,
	"lateralHeight": 10,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x7b3cc9da2395d5f7
// Course: 6th grade math
// Exercise: Nets of polyhedra
// Widget key: net_choice_d
test("polyhedron-net-diagram - Nets of polyhedra", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 6,
		"side2": 6,
		"height": 5
	},
	"width": 450,
	"height": 400,
	"showLabels": false,
	"lateralHeight": 7,
	"polyhedronType": "triangularPyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x392160cd92fe3e27
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"side": 3,
		"type": "square"
	},
	"width": 350,
	"height": 284,
	"showLabels": true,
	"polyhedronType": "cube",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xef2418627b5b28d2
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"side": 5,
		"type": "square"
	},
	"width": 350,
	"height": 327,
	"showLabels": true,
	"lateralHeight": 4,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xe873e79f79cfec78
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 5,
		"side2": 5,
		"height": 4
	},
	"width": 288,
	"height": 272,
	"showLabels": true,
	"lateralHeight": 7,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x6bf2799019a4c116
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"base": 4,
		"type": "triangle",
		"side1": 3,
		"side2": 5,
		"height": 3
	},
	"width": 256,
	"height": 304,
	"showLabels": false,
	"lateralHeight": 11,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x5045189399d8d4d7
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"type": "rectangle",
		"width": 2,
		"length": 7
	},
	"width": 400,
	"height": 191,
	"showLabels": false,
	"lateralHeight": 3,
	"polyhedronType": "rectangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x5fe595a08c112276
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"base": 4,
		"type": "triangle",
		"side1": 3,
		"side2": 5,
		"height": 3
	},
	"width": 256,
	"height": 240,
	"showLabels": false,
	"lateralHeight": 7,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xa031ac193d12bf61
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"side": 2,
		"type": "square"
	},
	"width": 338,
	"height": 338,
	"showLabels": false,
	"lateralHeight": 2,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x724a8e31845f5acf
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_1
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"side": 2,
		"type": "square"
	},
	"width": 350,
	"height": 280,
	"showLabels": false,
	"polyhedronType": "cube",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x8268530c631be46a
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"side": 3,
		"type": "square"
	},
	"width": 300,
	"height": 300,
	"showLabels": true,
	"lateralHeight": 4,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x349e37b6f7597ae5
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"side": 4,
		"type": "square"
	},
	"width": 350,
	"height": 280,
	"showLabels": true,
	"polyhedronType": "cube",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xdc67de44dab2c3e8
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"type": "rectangle",
		"width": 2,
		"length": 5
	},
	"width": 350,
	"height": 196,
	"showLabels": false,
	"lateralHeight": 2,
	"polyhedronType": "rectangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x64f0b3a6c49c33e2
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"type": "rectangle",
		"width": 2,
		"length": 3
	},
	"width": 300,
	"height": 238,
	"showLabels": false,
	"lateralHeight": 4,
	"polyhedronType": "rectangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xb8c8ec4d70f42920
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"base": 6,
		"type": "triangle",
		"side1": 3,
		"side2": 3,
		"height": 2
	},
	"width": 224,
	"height": 208,
	"showLabels": true,
	"lateralHeight": 7,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xcbc3b5f0e2dd746d
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_6
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"type": "rectangle",
		"width": 2,
		"length": 5
	},
	"width": 323,
	"height": 350,
	"showLabels": true,
	"lateralHeight": 3,
	"polyhedronType": "rectangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xca0bf838fcfa3f34
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"side": 5,
		"type": "square"
	},
	"width": 350,
	"height": 283,
	"showLabels": true,
	"polyhedronType": "cube",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x89ece9feb268fdc4
// Course: 6th grade math
// Exercise: Surface area using nets
// Widget key: image_2
test("polyhedron-net-diagram - Surface area using nets", () => {
	const input = {
	"base": {
		"side": 4,
		"type": "square"
	},
	"width": 300,
	"height": 300,
	"showLabels": true,
	"lateralHeight": 3,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xa2cc3aca85b395ce
// Course: 6th grade math
// Exercise: Surface area word problems
// Widget key: image_2
test("polyhedron-net-diagram - Surface area word problems", () => {
	const input = {
	"base": {
		"side": 13,
		"type": "square"
	},
	"width": 270,
	"height": 216,
	"showLabels": false,
	"polyhedronType": "cube",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x952422856d62c21e
// Course: 6th grade math
// Exercise: Surface area word problems
// Widget key: image_2
test("polyhedron-net-diagram - Surface area word problems", () => {
	const input = {
	"base": {
		"type": "rectangle",
		"width": 8,
		"length": 20
	},
	"width": 260,
	"height": 230,
	"showLabels": false,
	"lateralHeight": 30,
	"polyhedronType": "rectangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x0b1d59dfad3f9df4
// Course: 6th grade math
// Exercise: Surface area word problems
// Widget key: image_1
test("polyhedron-net-diagram - Surface area word problems", () => {
	const input = {
	"base": {
		"base": 1.2,
		"type": "triangle",
		"side1": 0.9,
		"side2": 1.5,
		"height": 0.9
	},
	"width": 227,
	"height": 320,
	"showLabels": false,
	"lateralHeight": 3.5,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: xe2a050cab649a32b
// Course: 6th grade math
// Exercise: Surface area word problems
// Widget key: image_1
test("polyhedron-net-diagram - Surface area word problems", () => {
	const input = {
	"base": {
		"base": 2,
		"type": "triangle",
		"side1": 2,
		"side2": 2,
		"height": 1.7
	},
	"width": 260,
	"height": 260,
	"showLabels": false,
	"lateralHeight": 3,
	"polyhedronType": "triangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x2c09a69cef8a52d6
// Course: 6th grade math
// Exercise: Surface area word problems
// Widget key: image_2
test("polyhedron-net-diagram - Surface area word problems", () => {
	const input = {
	"base": {
		"side": 70,
		"type": "square"
	},
	"width": 266,
	"height": 270,
	"showLabels": true,
	"lateralHeight": 140,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x93a0156c763196e7
// Course: 6th grade math
// Exercise: Surface area word problems
// Widget key: image_2
test("polyhedron-net-diagram - Surface area word problems", () => {
	const input = {
	"base": {
		"side": 25,
		"type": "square"
	},
	"width": 260,
	"height": 243,
	"showLabels": false,
	"lateralHeight": 30,
	"polyhedronType": "squarePyramid",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})


// Extracted from question: x05cfd2fe82c6be0e
// Course: 6th grade math
// Exercise: Surface area word problems
// Widget key: image_2
test("polyhedron-net-diagram - Surface area word problems", () => {
	const input = {
	"base": {
		"type": "rectangle",
		"width": 10,
		"length": 10
	},
	"width": 136,
	"height": 300,
	"showLabels": false,
	"lateralHeight": 90,
	"polyhedronType": "rectangularPrism",
	"type": "polyhedronNetDiagram"
} satisfies PolyhedronNetDiagramInput

	// Validate the input
	const parseResult = PolyhedronNetDiagramPropsSchema.safeParse(input)
	if (!parseResult.success) {
		console.error("Schema validation failed for extracted polyhedronNetDiagram:", parseResult.error)
		return
	}

	// Generate the widget
	const svg = generatePolyhedronNetDiagram(parseResult.data)
	expect(svg).toMatchSnapshot()
})

