// ============================================================================
// EXTRACTED TEST FILE - AUTO-GENERATED
// ============================================================================
// This file was automatically generated from database structured_json data
// Generated on: 2025-09-17T15:38:03.972Z
// Widget Type: rectangularFrameDiagram
// Source: Real questions from database
//
// These tests use actual widget configurations extracted from production data
// to ensure comprehensive test coverage with realistic scenarios.
//
// Note: Database data may not perfectly match current widget schemas, so these
// tests rely on runtime validation within generateWidget() for flexibility.
//
// DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten on regeneration
//
// Run tests: bun test tests/widgets/rectangular-frame-diagram.extracted.test.ts
// Update snapshots: bun test tests/widgets/rectangular-frame-diagram.extracted.test.ts --update-snapshots
// ============================================================================

import { describe, test, expect } from "bun:test"
import { generateWidget } from "@superbuilders/qti-assessment-item-generator/widgets/widget-generator"
import type { Widget, WidgetInput } from "@superbuilders/qti-assessment-item-generator/widgets/registry"
import * as errors from "@superbuilders/errors"
import * as logger from "@superbuilders/slog"

describe("rectangularFrameDiagram widget tests", () => {
	// Extracted from question: x335cbb4b025e09ae
	// Question: Find the area of the yard inside the fence
	// Widget key: image_1
	test("rectangular-frame-diagram - [x335cbb4b025e09ae] Find the area of the yard inside the fence", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "rectangularFrameDiagram",
		  "width": 240,
		  "height": 110,
		  "labels": [],
		  "diagonals": [],
		  "thickness": 1,
		  "outerWidth": 10,
		  "shadedFace": "front_face",
		  "outerHeight": 1.5,
		  "outerLength": 10,
		  "showHiddenEdges": true
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for rectangularFrameDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

})
