// ============================================================================
// EXTRACTED TEST FILE - AUTO-GENERATED
// ============================================================================
// This file was automatically generated from database structured_json data
// Generated on: 2025-09-18T05:17:02.169Z
// Widget Type: transformationDiagram
// Source: Real questions from database
//
// These tests use actual widget configurations extracted from production data
// to ensure comprehensive test coverage with realistic scenarios.
//
// Note: Database data may not perfectly match current widget schemas, so these
// tests rely on runtime validation within generateWidget() for flexibility.
//
// DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten on regeneration
//
// Run tests: bun test tests/widgets/transformation-diagram.extracted.test.ts
// Update snapshots: bun test tests/widgets/transformation-diagram.extracted.test.ts --update-snapshots
// ============================================================================

import { describe, test, expect } from "bun:test"
import { generateWidget } from "@superbuilders/qti-assessment-item-generator/widgets/widget-generator"
import type { Widget, WidgetInput } from "@superbuilders/qti-assessment-item-generator/widgets/registry"
import * as errors from "@superbuilders/errors"
import * as logger from "@superbuilders/slog"

describe("transformationDiagram widget tests", () => {
	// Extracted from question: x64eedd0feaf0a4e9
	// Question: Determine angles of rotation for a quadrilateral
	// Widget key: image_1
	test("transformation-diagram - [x64eedd0feaf0a4e9] Determine angles of rotation for a quadrilateral", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 300,
		  "height": 300,
		  "preImage": {
		    "label": "ABCD",
		    "vertices": [
		      {
		        "x": 85.714,
		        "y": 150
		      },
		      {
		        "x": 128.571,
		        "y": 128.571
		      },
		      {
		        "x": 42.857,
		        "y": 42.857
		      },
		      {
		        "x": 42.857,
		        "y": 107.143
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C",
		      "D"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": -90,
		    "centerOfRotation": {
		      "x": 150,
		      "y": 150
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x85b1af568c1e6a17
	// Question: Angles of rotation about a point
	// Widget key: image_1
	test("transformation-diagram - [x85b1af568c1e6a17] Angles of rotation about a point", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 325,
		  "height": 256,
		  "preImage": {
		    "label": "A, Q, A'",
		    "vertices": [
		      {
		        "x": 243.75,
		        "y": 81.25
		      },
		      {
		        "x": 150,
		        "y": 43.75
		      },
		      {
		        "x": 112.5,
		        "y": 137.5
		      }
		    ],
		    "fillColor": "#ffffff00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#888888",
		    "vertexLabels": [
		      "A",
		      "Q",
		      "A'"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 0,
		    "centerOfRotation": {
		      "x": 150,
		      "y": 43.75
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x1c6f03f93e701299
	// Question: Angles of rotation about a point
	// Widget key: image_1
	test("transformation-diagram - [x1c6f03f93e701299] Angles of rotation about a point", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 325,
		  "height": 201,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 131.25,
		        "y": 62.5
		      },
		      {
		        "x": 150,
		        "y": 100
		      },
		      {
		        "x": 187.5,
		        "y": 25
		      }
		    ],
		    "fillColor": "#FFE5F1",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#ca337c",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 90,
		    "centerOfRotation": {
		      "x": 150,
		      "y": 100
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x42fd94585aa7869b
	// Question: Determine the angle of rotation
	// Widget key: image_1
	test("transformation-diagram - [x42fd94585aa7869b] Determine the angle of rotation", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 325,
		  "height": 306.25,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 93.75,
		        "y": 231.25
		      },
		      {
		        "x": 75,
		        "y": 193.75
		      },
		      {
		        "x": 37.5,
		        "y": 250
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 180,
		    "centerOfRotation": {
		      "x": 150,
		      "y": 156.25
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x297abd97564f5023
	// Question: Determine angles of rotation from a diagram
	// Widget key: image_1
	test("transformation-diagram - [x297abd97564f5023] Determine angles of rotation from a diagram", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 325,
		  "height": 250,
		  "preImage": {
		    "label": "ABCD",
		    "vertices": [
		      {
		        "x": 187.5,
		        "y": 193.75
		      },
		      {
		        "x": 150,
		        "y": 212.5
		      },
		      {
		        "x": 56.25,
		        "y": 100
		      },
		      {
		        "x": 225,
		        "y": 118.75
		      }
		    ],
		    "fillColor": "#11accd33",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C",
		      "D"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 270,
		    "centerOfRotation": {
		      "x": 150,
		      "y": 137.5
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x35ae15324cadb751
	// Question: Identify the image after a 180-degree rotation
	// Widget key: image_1
	test("transformation-diagram - [x35ae15324cadb751] Identify the image after a 180-degree rotation (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 200,
		  "preImage": {
		    "label": "P",
		    "vertices": [
		      {
		        "x": 155.833,
		        "y": 42.5
		      },
		      {
		        "x": 141.667,
		        "y": 14.167
		      },
		      {
		        "x": 113.333,
		        "y": 42.5
		      }
		    ],
		    "fillColor": "#00000000",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      " ",
		      " ",
		      " "
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 0,
		    "centerOfRotation": {
		      "x": 85,
		      "y": 28.333
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x35ae15324cadb751
	// Question: Identify the image after a 180-degree rotation
	// Widget key: choice_a_diagram
	test("transformation-diagram - [x35ae15324cadb751] Identify the image after a 180-degree rotation (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "P",
		    "vertices": [
		      {
		        "x": 155.833,
		        "y": 99.167
		      },
		      {
		        "x": 141.667,
		        "y": 70.833
		      },
		      {
		        "x": 113.333,
		        "y": 99.167
		      }
		    ],
		    "fillColor": "#00000000",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      " ",
		      " ",
		      " "
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 180,
		    "centerOfRotation": {
		      "x": 85,
		      "y": 85
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x35ae15324cadb751
	// Question: Identify the image after a 180-degree rotation
	// Widget key: choice_b_diagram
	test("transformation-diagram - [x35ae15324cadb751] Identify the image after a 180-degree rotation (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "P",
		    "vertices": [
		      {
		        "x": 155.833,
		        "y": 99.167
		      },
		      {
		        "x": 141.667,
		        "y": 70.833
		      },
		      {
		        "x": 113.333,
		        "y": 99.167
		      }
		    ],
		    "fillColor": "#00000000",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      " ",
		      " ",
		      " "
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 150,
		    "centerOfRotation": {
		      "x": 85,
		      "y": 85
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x35ae15324cadb751
	// Question: Identify the image after a 180-degree rotation
	// Widget key: choice_c_diagram
	test("transformation-diagram - [x35ae15324cadb751] Identify the image after a 180-degree rotation (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "P",
		    "vertices": [
		      {
		        "x": 155.833,
		        "y": 99.167
		      },
		      {
		        "x": 141.667,
		        "y": 70.833
		      },
		      {
		        "x": 113.333,
		        "y": 99.167
		      }
		    ],
		    "fillColor": "#00000000",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      " ",
		      " ",
		      " "
		    ]
		  },
		  "transformation": {
		    "type": "translation",
		    "vector": {
		      "x": -96,
		      "y": 0
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x35ae15324cadb751
	// Question: Identify the image after a 180-degree rotation
	// Widget key: choice_d_diagram
	test("transformation-diagram - [x35ae15324cadb751] Identify the image after a 180-degree rotation (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "P",
		    "vertices": [
		      {
		        "x": 155.833,
		        "y": 99.167
		      },
		      {
		        "x": 141.667,
		        "y": 70.833
		      },
		      {
		        "x": 113.333,
		        "y": 99.167
		      }
		    ],
		    "fillColor": "#00000000",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      " ",
		      " ",
		      " "
		    ]
		  },
		  "transformation": {
		    "type": "translation",
		    "vector": {
		      "x": -96,
		      "y": -20
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x02d283b3a5235279
	// Question: Length of a segment after a rotation
	// Widget key: image_1
	test("transformation-diagram - [x02d283b3a5235279] Length of a segment after a rotation", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 350,
		  "height": 350,
		  "preImage": {
		    "label": "ABCD",
		    "vertices": [
		      {
		        "x": 116.667,
		        "y": 262.5
		      },
		      {
		        "x": 230.417,
		        "y": 291.667
		      },
		      {
		        "x": 87.5,
		        "y": 320.833
		      },
		      {
		        "x": 29.167,
		        "y": 262.5
		      }
		    ],
		    "fillColor": "#87CEFA55",
		    "angleMarks": [
		      {
		        "label": "123°",
		        "radius": 12,
		        "vertexIndex": 2,
		        "labelDistance": 18
		      }
		    ],
		    "sideLengths": [
		      {
		        "value": "",
		        "offset": 10,
		        "position": "outside"
		      },
		      {
		        "value": "5",
		        "offset": 10,
		        "position": "outside"
		      },
		      {
		        "value": "2.8",
		        "offset": 10,
		        "position": "outside"
		      },
		      {
		        "value": "",
		        "offset": 10,
		        "position": "outside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C",
		      "D"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 55,
		    "centerOfRotation": {
		      "x": 58.333,
		      "y": 87.5
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xfe0e823a7ded0a83
	// Question: Measure of an angle after a rotation
	// Widget key: image_1
	test("transformation-diagram - [xfe0e823a7ded0a83] Measure of an angle after a rotation", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 350,
		  "height": 318,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 140.061,
		        "y": 47.727
		      },
		      {
		        "x": 41.486,
		        "y": 27.555
		      },
		      {
		        "x": 147.445,
		        "y": 162.212
		      }
		    ],
		    "fillColor": "#ADD8E680",
		    "angleMarks": [
		      {
		        "label": "40°",
		        "radius": 18,
		        "vertexIndex": 0,
		        "labelDistance": 14
		      }
		    ],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": -120,
		    "centerOfRotation": {
		      "x": 222.727,
		      "y": 95.455
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xf613edebe37981e4
	// Question: Find the length of a segment after reflection
	// Widget key: image_1
	test("transformation-diagram - [xf613edebe37981e4] Find the length of a segment after reflection", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 323,
		  "height": 350,
		  "preImage": {
		    "label": "ABCD",
		    "vertices": [
		      {
		        "x": 296.154,
		        "y": 269.231
		      },
		      {
		        "x": 161.538,
		        "y": 323.077
		      },
		      {
		        "x": 188.462,
		        "y": 215.385
		      },
		      {
		        "x": 269.231,
		        "y": 188.462
		      }
		    ],
		    "fillColor": "#ADD8E680",
		    "angleMarks": [
		      {
		        "label": "90°",
		        "radius": 16,
		        "vertexIndex": 0,
		        "labelDistance": 20
		      },
		      {
		        "label": "93°",
		        "radius": 16,
		        "vertexIndex": 3,
		        "labelDistance": 20
		      }
		    ],
		    "sideLengths": [
		      {
		        "value": "32",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "41",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "54",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "",
		        "offset": 12,
		        "position": "outside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C",
		      "D"
		    ]
		  },
		  "transformation": {
		    "type": "reflection",
		    "lineOfReflection": {
		      "to": {
		        "x": 322.203,
		        "y": 81.352
		      },
		      "from": {
		        "x": 0,
		        "y": 296.154
		      },
		      "color": "#000000",
		      "style": "solid"
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x0611b8bfc546e264
	// Question: Measure of angle B after a translation
	// Widget key: image_1
	test("transformation-diagram - [x0611b8bfc546e264] Measure of angle B after a translation", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 350,
		  "height": 263,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 87.5,
		        "y": 29.167
		      },
		      {
		        "x": 29.167,
		        "y": 145.833
		      },
		      {
		        "x": 320.833,
		        "y": 204.167
		      }
		    ],
		    "fillColor": "#99c2ff80",
		    "angleMarks": [
		      {
		        "label": "80°",
		        "radius": 18,
		        "vertexIndex": 0,
		        "labelDistance": 22
		      },
		      {
		        "label": "26°",
		        "radius": 18,
		        "vertexIndex": 2,
		        "labelDistance": 22
		      }
		    ],
		    "sideLengths": [
		      {
		        "value": "2",
		        "offset": 0,
		        "position": "inside"
		      },
		      {
		        "value": "5",
		        "offset": 0,
		        "position": "inside"
		      },
		      {
		        "value": "",
		        "offset": 0,
		        "position": "inside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "translation",
		    "vector": {
		      "x": 5,
		      "y": 4
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x1ff6a2dddffe92c6
	// Question: Perimeter of a translated quadrilateral
	// Widget key: image_1
	test("transformation-diagram - [x1ff6a2dddffe92c6] Perimeter of a translated quadrilateral", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 350,
		  "height": 318,
		  "preImage": {
		    "label": "ABCD",
		    "vertices": [
		      {
		        "x": 127.273,
		        "y": 63.636
		      },
		      {
		        "x": 159.091,
		        "y": 127.273
		      },
		      {
		        "x": 286.364,
		        "y": 63.636
		      },
		      {
		        "x": 95.454,
		        "y": 31.818
		      }
		    ],
		    "fillColor": "#B3D5FF80",
		    "angleMarks": [],
		    "sideLengths": [
		      {
		        "value": "2.2",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "4.5",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "6.1",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "1.4",
		        "offset": 12,
		        "position": "outside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C",
		      "D"
		    ]
		  },
		  "transformation": {
		    "type": "translation",
		    "vector": {
		      "x": -2,
		      "y": -5
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x28a540bb2db4835d
	// Question: Find an angle measure after a reflection
	// Widget key: image_1
	test("transformation-diagram - [x28a540bb2db4835d] Find an angle measure after a reflection", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 350,
		  "height": 303,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 46.667,
		        "y": 116.667
		      },
		      {
		        "x": 140,
		        "y": 210
		      },
		      {
		        "x": 23.333,
		        "y": 256.667
		      }
		    ],
		    "fillColor": "#87CEFA55",
		    "angleMarks": [
		      {
		        "label": "59°",
		        "radius": 18,
		        "vertexIndex": 0,
		        "labelDistance": 24
		      },
		      {
		        "label": "67°",
		        "radius": 16,
		        "vertexIndex": 1,
		        "labelDistance": 22
		      }
		    ],
		    "sideLengths": [
		      {
		        "value": "",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "57",
		        "offset": 10,
		        "position": "outside"
		      },
		      {
		        "value": "61",
		        "offset": 10,
		        "position": "outside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "reflection",
		    "lineOfReflection": {
		      "to": {
		        "x": 221.197,
		        "y": 302.394
		      },
		      "from": {
		        "x": 70,
		        "y": 0
		      },
		      "color": "#000000",
		      "style": "solid"
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xbbbde7ff25ddf0ae
	// Question: Area of a rotated rectangle
	// Widget key: image_1
	test("transformation-diagram - [xbbbde7ff25ddf0ae] Area of a rotated rectangle", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 225,
		  "height": 350,
		  "preImage": {
		    "label": "ABCD",
		    "vertices": [
		      {
		        "x": 70,
		        "y": 240
		      },
		      {
		        "x": 190,
		        "y": 240
		      },
		      {
		        "x": 190,
		        "y": 260
		      },
		      {
		        "x": 70,
		        "y": 260
		      }
		    ],
		    "fillColor": "#ADD8E680",
		    "angleMarks": [],
		    "sideLengths": [
		      {
		        "value": "",
		        "offset": 0,
		        "position": "inside"
		      },
		      {
		        "value": "",
		        "offset": 0,
		        "position": "inside"
		      },
		      {
		        "value": "6",
		        "offset": 10,
		        "position": "outside"
		      },
		      {
		        "value": "",
		        "offset": 0,
		        "position": "inside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C",
		      "D"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 95,
		    "centerOfRotation": {
		      "x": 130,
		      "y": 150
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x1a7907dab800f3a1
	// Question: Perimeter after a rotation
	// Widget key: image_1
	test("transformation-diagram - [x1a7907dab800f3a1] Perimeter after a rotation", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 296.154,
		  "height": 350,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 33.418,
		        "y": 198.371
		      },
		      {
		        "x": 104.758,
		        "y": 315.66
		      },
		      {
		        "x": 155.357,
		        "y": 297.244
		      }
		    ],
		    "fillColor": "#4da3ff55",
		    "angleMarks": [
		      {
		        "label": "20°",
		        "radius": 22,
		        "vertexIndex": 0,
		        "labelDistance": 14
		      }
		    ],
		    "sideLengths": [
		      {
		        "value": "5.1",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "2",
		        "offset": 10,
		        "position": "outside"
		      },
		      {
		        "value": "5.8",
		        "offset": 12,
		        "position": "outside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 135,
		    "centerOfRotation": {
		      "x": 134.615,
		      "y": 161.538
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xce360a6f42b7c514
	// Question: Area of a translated right triangle
	// Widget key: image_1
	test("transformation-diagram - [xce360a6f42b7c514] Area of a translated right triangle", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 350,
		  "height": 318.182,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 318.182,
		        "y": 63.636
		      },
		      {
		        "x": 222.727,
		        "y": 254.545
		      },
		      {
		        "x": 286.364,
		        "y": 286.364
		      }
		    ],
		    "fillColor": "#cfe8ff80",
		    "angleMarks": [
		      {
		        "label": "18°",
		        "radius": 20,
		        "vertexIndex": 0,
		        "labelDistance": 14
		      }
		    ],
		    "sideLengths": [
		      {
		        "value": "6.1 units",
		        "offset": 10,
		        "position": "outside"
		      },
		      {
		        "value": "2 units",
		        "offset": 10,
		        "position": "outside"
		      },
		      {
		        "value": "",
		        "offset": 10,
		        "position": "outside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "translation",
		    "vector": {
		      "x": -190.909,
		      "y": -31.818
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x49bbe652d98dba9b
	// Question: Area of a reflected triangle
	// Widget key: image_1
	test("transformation-diagram - [x49bbe652d98dba9b] Area of a reflected triangle", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 286.364,
		  "height": 350,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 31.818,
		        "y": 127.273
		      },
		      {
		        "x": 159.091,
		        "y": 127.273
		      },
		      {
		        "x": 159.091,
		        "y": 31.818
		      }
		    ],
		    "fillColor": "#00000000",
		    "angleMarks": [],
		    "sideLengths": [
		      {
		        "value": "3",
		        "offset": 10,
		        "position": "inside"
		      },
		      {
		        "value": "4",
		        "offset": 10,
		        "position": "inside"
		      },
		      {
		        "value": "",
		        "offset": 10,
		        "position": "inside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "C",
		      "A",
		      "B"
		    ]
		  },
		  "transformation": {
		    "type": "reflection",
		    "lineOfReflection": {
		      "to": {
		        "x": 286.364,
		        "y": 148.485
		      },
		      "from": {
		        "x": 0.996,
		        "y": 243.607
		      },
		      "color": "#000000",
		      "style": "solid"
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xfebb6b0033d5b89b
	// Question: Length of a translated segment
	// Widget key: image_1
	test("transformation-diagram - [xfebb6b0033d5b89b] Length of a translated segment", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 350,
		  "height": 239,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 280,
		        "y": 180
		      },
		      {
		        "x": 330,
		        "y": 100
		      },
		      {
		        "x": 250,
		        "y": 60
		      }
		    ],
		    "fillColor": "#6495ED40",
		    "angleMarks": [],
		    "sideLengths": [
		      {
		        "value": "8",
		        "offset": 12,
		        "position": "inside"
		      },
		      {
		        "value": "9",
		        "offset": 12,
		        "position": "inside"
		      },
		      {
		        "value": "6",
		        "offset": 12,
		        "position": "inside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "translation",
		    "vector": {
		      "x": -120,
		      "y": -60
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x889f3d155d57ca53
	// Question: Perimeter of a reflected quadrilateral
	// Widget key: image_1
	test("transformation-diagram - [x889f3d155d57ca53] Perimeter of a reflected quadrilateral", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 350,
		  "height": 254.545,
		  "preImage": {
		    "label": "ABCD",
		    "vertices": [
		      {
		        "x": 95.454,
		        "y": 222.727
		      },
		      {
		        "x": 31.818,
		        "y": 190.909
		      },
		      {
		        "x": 31.818,
		        "y": 127.273
		      },
		      {
		        "x": 127.273,
		        "y": 127.273
		      }
		    ],
		    "fillColor": "#6495ed55",
		    "angleMarks": [],
		    "sideLengths": [
		      {
		        "value": "22",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "20",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "30",
		        "offset": 12,
		        "position": "outside"
		      },
		      {
		        "value": "32",
		        "offset": 12,
		        "position": "outside"
		      }
		    ],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C",
		      "D"
		    ]
		  },
		  "transformation": {
		    "type": "reflection",
		    "lineOfReflection": {
		      "to": {
		        "x": 212.121,
		        "y": 254.545
		      },
		      "from": {
		        "x": 127.273,
		        "y": 0
		      },
		      "color": "#000000",
		      "style": "solid"
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xd3a4d32a5fee1c24
	// Question: Scaled copy: possible corresponding side length
	// Widget key: image_1
	test("transformation-diagram - [xd3a4d32a5fee1c24] Scaled copy: possible corresponding side length", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 488,
		  "height": 500,
		  "preImage": {
		    "label": "ABCD",
		    "vertices": [
		      {
		        "x": 35.294,
		        "y": 94.118
		      },
		      {
		        "x": 152.941,
		        "y": 35.294
		      },
		      {
		        "x": 94.118,
		        "y": 94.118
		      },
		      {
		        "x": 152.941,
		        "y": 152.941
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [
		      {
		        "value": "",
		        "offset": 8,
		        "position": "outside"
		      },
		      {
		        "value": "",
		        "offset": 8,
		        "position": "outside"
		      },
		      {
		        "value": "",
		        "offset": 8,
		        "position": "outside"
		      },
		      {
		        "value": "16 units",
		        "offset": 10,
		        "position": "outside"
		      }
		    ],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C",
		      "D"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 1,
		    "centerOfDilation": {
		      "x": 0,
		      "y": 0
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x47365ede15825ef1
	// Question: Identify the image of a triangle under a dilation
	// Widget key: choice_a_figure
	test("transformation-diagram - [x47365ede15825ef1] Identify the image of a triangle under a dilation (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 119,
		        "y": 51
		      },
		      {
		        "x": 119,
		        "y": 119
		      },
		      {
		        "x": 68,
		        "y": 85
		      }
		    ],
		    "fillColor": "#ffffff",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.67,
		    "centerOfDilation": {
		      "x": 119,
		      "y": 85
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x47365ede15825ef1
	// Question: Identify the image of a triangle under a dilation
	// Widget key: choice_b_figure
	test("transformation-diagram - [x47365ede15825ef1] Identify the image of a triangle under a dilation (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 119,
		        "y": 51
		      },
		      {
		        "x": 119,
		        "y": 119
		      },
		      {
		        "x": 68,
		        "y": 85
		      }
		    ],
		    "fillColor": "#ffffff",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 1.5,
		    "centerOfDilation": {
		      "x": 119,
		      "y": 85
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x47365ede15825ef1
	// Question: Identify the image of a triangle under a dilation
	// Widget key: choice_c_figure
	test("transformation-diagram - [x47365ede15825ef1] Identify the image of a triangle under a dilation (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 119,
		        "y": 51
		      },
		      {
		        "x": 119,
		        "y": 119
		      },
		      {
		        "x": 68,
		        "y": 85
		      }
		    ],
		    "fillColor": "#ffffff",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 1.5,
		    "centerOfDilation": {
		      "x": 68,
		      "y": 85
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x47365ede15825ef1
	// Question: Identify the image of a triangle under a dilation
	// Widget key: choice_d_figure
	test("transformation-diagram - [x47365ede15825ef1] Identify the image of a triangle under a dilation (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 119,
		        "y": 51
		      },
		      {
		        "x": 119,
		        "y": 119
		      },
		      {
		        "x": 68,
		        "y": 85
		      }
		    ],
		    "fillColor": "#ffffff",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.67,
		    "centerOfDilation": {
		      "x": 68,
		      "y": 85
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x604c7c450eb40990
	// Question: Identify the image of a triangle under dilation
	// Widget key: choice_a_figure
	test("transformation-diagram - [x604c7c450eb40990] Identify the image of a triangle under dilation (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 340,
		  "height": 340,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 102,
		        "y": 51
		      },
		      {
		        "x": 136,
		        "y": 102
		      },
		      {
		        "x": 51,
		        "y": 136
		      }
		    ],
		    "fillColor": "#FFFFFF",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.6666666667,
		    "centerOfDilation": {
		      "x": 102,
		      "y": 102
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x604c7c450eb40990
	// Question: Identify the image of a triangle under dilation
	// Widget key: choice_b_figure
	test("transformation-diagram - [x604c7c450eb40990] Identify the image of a triangle under dilation (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 340,
		  "height": 340,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 102,
		        "y": 51
		      },
		      {
		        "x": 136,
		        "y": 102
		      },
		      {
		        "x": 51,
		        "y": 136
		      }
		    ],
		    "fillColor": "#FFFFFF",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 1.3333333333,
		    "centerOfDilation": {
		      "x": 102,
		      "y": 102
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x604c7c450eb40990
	// Question: Identify the image of a triangle under dilation
	// Widget key: choice_c_figure
	test("transformation-diagram - [x604c7c450eb40990] Identify the image of a triangle under dilation (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 340,
		  "height": 340,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 102,
		        "y": 51
		      },
		      {
		        "x": 136,
		        "y": 102
		      },
		      {
		        "x": 51,
		        "y": 136
		      }
		    ],
		    "fillColor": "#FFFFFF",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 1.3333333333,
		    "centerOfDilation": {
		      "x": 136,
		      "y": 102
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x604c7c450eb40990
	// Question: Identify the image of a triangle under dilation
	// Widget key: choice_d_figure
	test("transformation-diagram - [x604c7c450eb40990] Identify the image of a triangle under dilation (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 340,
		  "height": 340,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 102,
		        "y": 51
		      },
		      {
		        "x": 136,
		        "y": 102
		      },
		      {
		        "x": 51,
		        "y": 136
		      }
		    ],
		    "fillColor": "#FFFFFF",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.6666666667,
		    "centerOfDilation": {
		      "x": 136,
		      "y": 102
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc0c504fedb55ca58
	// Question: Identify a dilation image with scale factor 1/4
	// Widget key: image_1
	test("transformation-diagram - [xc0c504fedb55ca58] Identify a dilation image with scale factor 1/4 (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 230,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 145.714,
		        "y": 48.571
		      },
		      {
		        "x": 145.714,
		        "y": 113.333
		      },
		      {
		        "x": 48.571,
		        "y": 32.381
		      }
		    ],
		    "fillColor": "#FFFFFF",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 1,
		    "centerOfDilation": {
		      "x": 145.714,
		      "y": 80.952
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc0c504fedb55ca58
	// Question: Identify a dilation image with scale factor 1/4
	// Widget key: choice_a_figure
	test("transformation-diagram - [xc0c504fedb55ca58] Identify a dilation image with scale factor 1/4 (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 230,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 145.714,
		        "y": 48.571
		      },
		      {
		        "x": 145.714,
		        "y": 113.333
		      },
		      {
		        "x": 48.571,
		        "y": 32.381
		      }
		    ],
		    "fillColor": "#FFFFFF",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.75,
		    "centerOfDilation": {
		      "x": 145.714,
		      "y": 80.952
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc0c504fedb55ca58
	// Question: Identify a dilation image with scale factor 1/4
	// Widget key: choice_b_figure
	test("transformation-diagram - [xc0c504fedb55ca58] Identify a dilation image with scale factor 1/4 (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 230,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 145.714,
		        "y": 48.571
		      },
		      {
		        "x": 145.714,
		        "y": 113.333
		      },
		      {
		        "x": 48.571,
		        "y": 32.381
		      }
		    ],
		    "fillColor": "#FFFFFF",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.25,
		    "centerOfDilation": {
		      "x": 145.714,
		      "y": 80.952
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc0c504fedb55ca58
	// Question: Identify a dilation image with scale factor 1/4
	// Widget key: choice_c_figure
	test("transformation-diagram - [xc0c504fedb55ca58] Identify a dilation image with scale factor 1/4 (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 230,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 145.714,
		        "y": 48.571
		      },
		      {
		        "x": 145.714,
		        "y": 113.333
		      },
		      {
		        "x": 48.571,
		        "y": 32.381
		      }
		    ],
		    "fillColor": "#FFFFFF",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.25,
		    "centerOfDilation": {
		      "x": 145.714,
		      "y": 48.571
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc0c504fedb55ca58
	// Question: Identify a dilation image with scale factor 1/4
	// Widget key: choice_d_figure
	test("transformation-diagram - [xc0c504fedb55ca58] Identify a dilation image with scale factor 1/4 (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 230,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 145.714,
		        "y": 48.571
		      },
		      {
		        "x": 145.714,
		        "y": 113.333
		      },
		      {
		        "x": 48.571,
		        "y": 32.381
		      }
		    ],
		    "fillColor": "#FFFFFF",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.75,
		    "centerOfDilation": {
		      "x": 145.714,
		      "y": 48.571
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x6654329a81441075
	// Question: Identify the dilated image of a triangle (center A, scale factor 3/4)
	// Widget key: choice_a_visual
	test("transformation-diagram - [x6654329a81441075] Identify the dilated image of a triangle (center A, scale factor 3/4) (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 500,
		  "height": 450,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 440,
		        "y": 80
		      },
		      {
		        "x": 360,
		        "y": 420
		      },
		      {
		        "x": 120,
		        "y": 260
		      }
		    ],
		    "fillColor": "#ffffff00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.35,
		    "centerOfDilation": {
		      "x": 440,
		      "y": 80
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x6654329a81441075
	// Question: Identify the dilated image of a triangle (center A, scale factor 3/4)
	// Widget key: choice_b_visual
	test("transformation-diagram - [x6654329a81441075] Identify the dilated image of a triangle (center A, scale factor 3/4) (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 500,
		  "height": 450,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 440,
		        "y": 80
		      },
		      {
		        "x": 360,
		        "y": 420
		      },
		      {
		        "x": 120,
		        "y": 260
		      }
		    ],
		    "fillColor": "#ffffff00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.75,
		    "centerOfDilation": {
		      "x": 440,
		      "y": 80
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x6654329a81441075
	// Question: Identify the dilated image of a triangle (center A, scale factor 3/4)
	// Widget key: choice_c_visual
	test("transformation-diagram - [x6654329a81441075] Identify the dilated image of a triangle (center A, scale factor 3/4) (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 500,
		  "height": 450,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 440,
		        "y": 80
		      },
		      {
		        "x": 360,
		        "y": 420
		      },
		      {
		        "x": 120,
		        "y": 260
		      }
		    ],
		    "fillColor": "#ffffff00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.45,
		    "centerOfDilation": {
		      "x": 300,
		      "y": 250
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x6654329a81441075
	// Question: Identify the dilated image of a triangle (center A, scale factor 3/4)
	// Widget key: choice_d_visual
	test("transformation-diagram - [x6654329a81441075] Identify the dilated image of a triangle (center A, scale factor 3/4) (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 500,
		  "height": 450,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 440,
		        "y": 80
		      },
		      {
		        "x": 360,
		        "y": 420
		      },
		      {
		        "x": 120,
		        "y": 260
		      }
		    ],
		    "fillColor": "#ffffff00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#000000",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.3,
		    "centerOfDilation": {
		      "x": 300,
		      "y": 200
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x42af57ec523a07d4
	// Question: Identify the image of a dilation (scale factor 1/3)
	// Widget key: choice_a_figure
	test("transformation-diagram - [x42af57ec523a07d4] Identify the image of a dilation (scale factor 1/3) (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 17,
		        "y": 34
		      },
		      {
		        "x": 136,
		        "y": 68
		      },
		      {
		        "x": 68,
		        "y": 153
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.8,
		    "centerOfDilation": {
		      "x": 85,
		      "y": 85
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x42af57ec523a07d4
	// Question: Identify the image of a dilation (scale factor 1/3)
	// Widget key: choice_b_figure
	test("transformation-diagram - [x42af57ec523a07d4] Identify the image of a dilation (scale factor 1/3) (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 17,
		        "y": 34
		      },
		      {
		        "x": 136,
		        "y": 68
		      },
		      {
		        "x": 68,
		        "y": 153
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.3333333333,
		    "centerOfDilation": {
		      "x": 85,
		      "y": 85
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x42af57ec523a07d4
	// Question: Identify the image of a dilation (scale factor 1/3)
	// Widget key: choice_c_figure
	test("transformation-diagram - [x42af57ec523a07d4] Identify the image of a dilation (scale factor 1/3) (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 17,
		        "y": 34
		      },
		      {
		        "x": 136,
		        "y": 68
		      },
		      {
		        "x": 68,
		        "y": 153
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.3333333333,
		    "centerOfDilation": {
		      "x": 42.5,
		      "y": 93.5
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x42af57ec523a07d4
	// Question: Identify the image of a dilation (scale factor 1/3)
	// Widget key: choice_d_figure
	test("transformation-diagram - [x42af57ec523a07d4] Identify the image of a dilation (scale factor 1/3) (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 17,
		        "y": 34
		      },
		      {
		        "x": 136,
		        "y": 68
		      },
		      {
		        "x": 68,
		        "y": 153
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.8,
		    "centerOfDilation": {
		      "x": 42.5,
		      "y": 93.5
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xbc50b5a72210c4cc
	// Question: Identify the image of a triangle under dilation (scale factor 2/3)
	// Widget key: image_1
	test("transformation-diagram - [xbc50b5a72210c4cc] Identify the image of a triangle under dilation (scale factor 2/3) (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 51,
		        "y": 34
		      },
		      {
		        "x": 102,
		        "y": 34
		      },
		      {
		        "x": 51,
		        "y": 136
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "rotation",
		    "angle": 0,
		    "centerOfRotation": {
		      "x": 136,
		      "y": 136
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xbc50b5a72210c4cc
	// Question: Identify the image of a triangle under dilation (scale factor 2/3)
	// Widget key: choice_a_visual
	test("transformation-diagram - [xbc50b5a72210c4cc] Identify the image of a triangle under dilation (scale factor 2/3) (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 51,
		        "y": 34
		      },
		      {
		        "x": 102,
		        "y": 34
		      },
		      {
		        "x": 51,
		        "y": 136
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.4,
		    "centerOfDilation": {
		      "x": 136,
		      "y": 136
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xbc50b5a72210c4cc
	// Question: Identify the image of a triangle under dilation (scale factor 2/3)
	// Widget key: choice_b_visual
	test("transformation-diagram - [xbc50b5a72210c4cc] Identify the image of a triangle under dilation (scale factor 2/3) (3)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 51,
		        "y": 34
		      },
		      {
		        "x": 102,
		        "y": 34
		      },
		      {
		        "x": 51,
		        "y": 136
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.6666666667,
		    "centerOfDilation": {
		      "x": 136,
		      "y": 136
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xbc50b5a72210c4cc
	// Question: Identify the image of a triangle under dilation (scale factor 2/3)
	// Widget key: choice_c_visual
	test("transformation-diagram - [xbc50b5a72210c4cc] Identify the image of a triangle under dilation (scale factor 2/3) (4)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 51,
		        "y": 34
		      },
		      {
		        "x": 102,
		        "y": 34
		      },
		      {
		        "x": 51,
		        "y": 136
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.6666666667,
		    "centerOfDilation": {
		      "x": 102,
		      "y": 34
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xbc50b5a72210c4cc
	// Question: Identify the image of a triangle under dilation (scale factor 2/3)
	// Widget key: choice_d_visual
	test("transformation-diagram - [xbc50b5a72210c4cc] Identify the image of a triangle under dilation (scale factor 2/3) (5)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "transformationDiagram",
		  "width": 270,
		  "height": 270,
		  "preImage": {
		    "label": "ABC",
		    "vertices": [
		      {
		        "x": 51,
		        "y": 34
		      },
		      {
		        "x": 102,
		        "y": 34
		      },
		      {
		        "x": 51,
		        "y": 136
		      }
		    ],
		    "fillColor": "#FFFFFF00",
		    "angleMarks": [],
		    "sideLengths": [],
		    "strokeColor": "#11accd",
		    "vertexLabels": [
		      "A",
		      "B",
		      "C"
		    ]
		  },
		  "transformation": {
		    "type": "dilation",
		    "scaleFactor": 0.4,
		    "centerOfDilation": {
		      "x": 102,
		      "y": 34
		    }
		  }
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for transformationDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

})
