// ============================================================================
// EXTRACTED TEST FILE - AUTO-GENERATED
// ============================================================================
// This file was automatically generated from database structured_json data
// Generated on: 2025-09-18T05:17:02.168Z
// Widget Type: treeDiagram
// Source: Real questions from database
//
// These tests use actual widget configurations extracted from production data
// to ensure comprehensive test coverage with realistic scenarios.
//
// Note: Database data may not perfectly match current widget schemas, so these
// tests rely on runtime validation within generateWidget() for flexibility.
//
// DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten on regeneration
//
// Run tests: bun test tests/widgets/tree-diagram.extracted.test.ts
// Update snapshots: bun test tests/widgets/tree-diagram.extracted.test.ts --update-snapshots
// ============================================================================

import { describe, test, expect } from "bun:test"
import { generateWidget } from "@superbuilders/qti-assessment-item-generator/widgets/widget-generator"
import type { Widget, WidgetInput } from "@superbuilders/qti-assessment-item-generator/widgets/registry"
import * as errors from "@superbuilders/errors"
import * as logger from "@superbuilders/slog"

describe("treeDiagram widget tests", () => {
	// Extracted from question: xffe5660467b89a5c
	// Question: Which display correctly represents the sample space?
	// Widget key: image_1
	test("tree-diagram - [xffe5660467b89a5c] Which display correctly represents the sample space?", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "p",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "r",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "b",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "p_l",
		      "from": "p",
		      "style": "solid"
		    },
		    {
		      "to": "p_u",
		      "from": "p",
		      "style": "solid"
		    },
		    {
		      "to": "r_l",
		      "from": "r",
		      "style": "solid"
		    },
		    {
		      "to": "r_u",
		      "from": "r",
		      "style": "solid"
		    },
		    {
		      "to": "b_l",
		      "from": "b",
		      "style": "solid"
		    },
		    {
		      "to": "b_u",
		      "from": "b",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": null,
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 40
		      }
		    },
		    {
		      "id": "p",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 100,
		        "y": 110
		      }
		    },
		    {
		      "id": "r",
		      "color": "#000000",
		      "label": "R",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 110
		      }
		    },
		    {
		      "id": "b",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 340,
		        "y": 110
		      }
		    },
		    {
		      "id": "p_l",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 60,
		        "y": 220
		      }
		    },
		    {
		      "id": "p_u",
		      "color": "#000000",
		      "label": "U",
		      "style": "circled",
		      "position": {
		        "x": 140,
		        "y": 220
		      }
		    },
		    {
		      "id": "r_l",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 180,
		        "y": 220
		      }
		    },
		    {
		      "id": "r_u",
		      "color": "#000000",
		      "label": "U",
		      "style": "circled",
		      "position": {
		        "x": 260,
		        "y": 220
		      }
		    },
		    {
		      "id": "b_l",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 300,
		        "y": 220
		      }
		    },
		    {
		      "id": "b_u",
		      "color": "#000000",
		      "label": "U",
		      "style": "circled",
		      "position": {
		        "x": 380,
		        "y": 220
		      }
		    }
		  ],
		  "width": 440,
		  "height": 300,
		  "nodeRadius": 20,
		  "nodeFontSize": 14
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa32758572502b4bd
	// Question: Tree diagrams for pizza combinations
	// Widget key: image_1
	test("tree-diagram - [xa32758572502b4bd] Tree diagrams for pizza combinations (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "t",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "d",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "t_p",
		      "from": "t",
		      "style": "solid"
		    },
		    {
		      "to": "t_c",
		      "from": "t",
		      "style": "solid"
		    },
		    {
		      "to": "t_m",
		      "from": "t",
		      "style": "solid"
		    },
		    {
		      "to": "d_p",
		      "from": "d",
		      "style": "solid"
		    },
		    {
		      "to": "d_c",
		      "from": "d",
		      "style": "solid"
		    },
		    {
		      "to": "d_m",
		      "from": "d",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": null,
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 30
		      }
		    },
		    {
		      "id": "t",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 90
		      }
		    },
		    {
		      "id": "d",
		      "color": "#000000",
		      "label": "D",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 90
		      }
		    },
		    {
		      "id": "t_p",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 53.2,
		        "y": 190
		      }
		    },
		    {
		      "id": "t_c",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 190
		      }
		    },
		    {
		      "id": "t_m",
		      "color": "#000000",
		      "label": "M",
		      "style": "circled",
		      "position": {
		        "x": 186.8,
		        "y": 190
		      }
		    },
		    {
		      "id": "d_p",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 253.2,
		        "y": 190
		      }
		    },
		    {
		      "id": "d_c",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 190
		      }
		    },
		    {
		      "id": "d_m",
		      "color": "#000000",
		      "label": "M",
		      "style": "circled",
		      "position": {
		        "x": 386.8,
		        "y": 190
		      }
		    }
		  ],
		  "width": 440,
		  "height": 304,
		  "nodeRadius": 20,
		  "nodeFontSize": 16
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa32758572502b4bd
	// Question: Tree diagrams for pizza combinations
	// Widget key: image_2
	test("tree-diagram - [xa32758572502b4bd] Tree diagrams for pizza combinations (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "p",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "m",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "c",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "p_t",
		      "from": "p",
		      "style": "solid"
		    },
		    {
		      "to": "p_d",
		      "from": "p",
		      "style": "solid"
		    },
		    {
		      "to": "m_t",
		      "from": "m",
		      "style": "solid"
		    },
		    {
		      "to": "m_d",
		      "from": "m",
		      "style": "solid"
		    },
		    {
		      "to": "c_t",
		      "from": "c",
		      "style": "solid"
		    },
		    {
		      "to": "c_d",
		      "from": "c",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": null,
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 30
		      }
		    },
		    {
		      "id": "p",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 86.8,
		        "y": 90
		      }
		    },
		    {
		      "id": "m",
		      "color": "#000000",
		      "label": "M",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 90
		      }
		    },
		    {
		      "id": "c",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 353.2,
		        "y": 90
		      }
		    },
		    {
		      "id": "p_t",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 53.2,
		        "y": 190
		      }
		    },
		    {
		      "id": "p_d",
		      "color": "#000000",
		      "label": "D",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 190
		      }
		    },
		    {
		      "id": "m_t",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 186.8,
		        "y": 190
		      }
		    },
		    {
		      "id": "m_d",
		      "color": "#000000",
		      "label": "D",
		      "style": "circled",
		      "position": {
		        "x": 253.2,
		        "y": 190
		      }
		    },
		    {
		      "id": "c_t",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 190
		      }
		    },
		    {
		      "id": "c_d",
		      "color": "#000000",
		      "label": "D",
		      "style": "circled",
		      "position": {
		        "x": 386.8,
		        "y": 190
		      }
		    }
		  ],
		  "width": 440,
		  "height": 304,
		  "nodeRadius": 20,
		  "nodeFontSize": 16
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xfced0271e1570dd0
	// Question: Select the correct sample space display
	// Widget key: image_2
	test("tree-diagram - [xfced0271e1570dd0] Select the correct sample space display", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "B1",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "T1",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "P1",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "B1_B",
		      "from": "B1",
		      "style": "solid"
		    },
		    {
		      "to": "B1_T",
		      "from": "B1",
		      "style": "solid"
		    },
		    {
		      "to": "B1_P",
		      "from": "B1",
		      "style": "solid"
		    },
		    {
		      "to": "T1_B",
		      "from": "T1",
		      "style": "solid"
		    },
		    {
		      "to": "T1_T",
		      "from": "T1",
		      "style": "solid"
		    },
		    {
		      "to": "T1_P",
		      "from": "T1",
		      "style": "solid"
		    },
		    {
		      "to": "P1_B",
		      "from": "P1",
		      "style": "solid"
		    },
		    {
		      "to": "P1_T",
		      "from": "P1",
		      "style": "solid"
		    },
		    {
		      "to": "P1_P",
		      "from": "P1",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": " ",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 40
		      }
		    },
		    {
		      "id": "B1",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 100,
		        "y": 100
		      }
		    },
		    {
		      "id": "T1",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 100
		      }
		    },
		    {
		      "id": "P1",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 340,
		        "y": 100
		      }
		    },
		    {
		      "id": "B1_B",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 40,
		        "y": 200
		      }
		    },
		    {
		      "id": "B1_T",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 100,
		        "y": 200
		      }
		    },
		    {
		      "id": "B1_P",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 160,
		        "y": 200
		      }
		    },
		    {
		      "id": "T1_B",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 180,
		        "y": 200
		      }
		    },
		    {
		      "id": "T1_T",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 200
		      }
		    },
		    {
		      "id": "T1_P",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 260,
		        "y": 200
		      }
		    },
		    {
		      "id": "P1_B",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 300,
		        "y": 200
		      }
		    },
		    {
		      "id": "P1_T",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 340,
		        "y": 200
		      }
		    },
		    {
		      "id": "P1_P",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 380,
		        "y": 200
		      }
		    }
		  ],
		  "width": 440,
		  "height": 300,
		  "nodeRadius": 20,
		  "nodeFontSize": 16
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xcfc0bdb0990dfe10
	// Question: Choose the tree diagram for 3 random steps
	// Widget key: diagram_choice_a
	test("tree-diagram - [xcfc0bdb0990dfe10] Choose the tree diagram for 3 random steps (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "out3L",
		      "from": "rootA",
		      "style": "solid"
		    },
		    {
		      "to": "out2L1R",
		      "from": "rootA",
		      "style": "solid"
		    },
		    {
		      "to": "out1L2R",
		      "from": "rootA",
		      "style": "solid"
		    },
		    {
		      "to": "out3R",
		      "from": "rootA",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "rootA",
		      "color": "#000000",
		      "label": null,
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 40
		      }
		    },
		    {
		      "id": "out3L",
		      "color": "#000000",
		      "label": "3 Lefts",
		      "style": "circled",
		      "position": {
		        "x": 70,
		        "y": 240
		      }
		    },
		    {
		      "id": "out2L1R",
		      "color": "#000000",
		      "label": "2 Lefts 1 Right",
		      "style": "circled",
		      "position": {
		        "x": 170,
		        "y": 240
		      }
		    },
		    {
		      "id": "out1L2R",
		      "color": "#000000",
		      "label": "1 Left 2 Rights",
		      "style": "circled",
		      "position": {
		        "x": 270,
		        "y": 240
		      }
		    },
		    {
		      "id": "out3R",
		      "color": "#000000",
		      "label": "3 Rights",
		      "style": "circled",
		      "position": {
		        "x": 370,
		        "y": 240
		      }
		    }
		  ],
		  "width": 440,
		  "height": 320,
		  "nodeRadius": 38,
		  "nodeFontSize": 12
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xcfc0bdb0990dfe10
	// Question: Choose the tree diagram for 3 random steps
	// Widget key: diagram_choice_b
	test("tree-diagram - [xcfc0bdb0990dfe10] Choose the tree diagram for 3 random steps (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "l1",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "r1",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "ll",
		      "from": "l1",
		      "style": "solid"
		    },
		    {
		      "to": "lr",
		      "from": "l1",
		      "style": "solid"
		    },
		    {
		      "to": "rl",
		      "from": "r1",
		      "style": "solid"
		    },
		    {
		      "to": "rr",
		      "from": "r1",
		      "style": "solid"
		    },
		    {
		      "to": "lll",
		      "from": "ll",
		      "style": "solid"
		    },
		    {
		      "to": "llr",
		      "from": "ll",
		      "style": "solid"
		    },
		    {
		      "to": "lrl",
		      "from": "lr",
		      "style": "solid"
		    },
		    {
		      "to": "lrr",
		      "from": "lr",
		      "style": "solid"
		    },
		    {
		      "to": "rll",
		      "from": "rl",
		      "style": "solid"
		    },
		    {
		      "to": "rlr",
		      "from": "rl",
		      "style": "solid"
		    },
		    {
		      "to": "rrl",
		      "from": "rr",
		      "style": "solid"
		    },
		    {
		      "to": "rrr",
		      "from": "rr",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": null,
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 40
		      }
		    },
		    {
		      "id": "l1",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 100
		      }
		    },
		    {
		      "id": "r1",
		      "color": "#000000",
		      "label": "R",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 100
		      }
		    },
		    {
		      "id": "ll",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 70,
		        "y": 180
		      }
		    },
		    {
		      "id": "lr",
		      "color": "#000000",
		      "label": "R",
		      "style": "circled",
		      "position": {
		        "x": 170,
		        "y": 180
		      }
		    },
		    {
		      "id": "rl",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 270,
		        "y": 180
		      }
		    },
		    {
		      "id": "rr",
		      "color": "#000000",
		      "label": "R",
		      "style": "circled",
		      "position": {
		        "x": 370,
		        "y": 180
		      }
		    },
		    {
		      "id": "lll",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 45,
		        "y": 260
		      }
		    },
		    {
		      "id": "llr",
		      "color": "#000000",
		      "label": "R",
		      "style": "circled",
		      "position": {
		        "x": 95,
		        "y": 260
		      }
		    },
		    {
		      "id": "lrl",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 145,
		        "y": 260
		      }
		    },
		    {
		      "id": "lrr",
		      "color": "#000000",
		      "label": "R",
		      "style": "circled",
		      "position": {
		        "x": 195,
		        "y": 260
		      }
		    },
		    {
		      "id": "rll",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 245,
		        "y": 260
		      }
		    },
		    {
		      "id": "rlr",
		      "color": "#000000",
		      "label": "R",
		      "style": "circled",
		      "position": {
		        "x": 295,
		        "y": 260
		      }
		    },
		    {
		      "id": "rrl",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 345,
		        "y": 260
		      }
		    },
		    {
		      "id": "rrr",
		      "color": "#000000",
		      "label": "R",
		      "style": "circled",
		      "position": {
		        "x": 395,
		        "y": 260
		      }
		    }
		  ],
		  "width": 440,
		  "height": 308,
		  "nodeRadius": 20,
		  "nodeFontSize": 12
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x150b1c6c6e15ce1f
	// Question: Choose the correct tree diagram for three coin flips
	// Widget key: image_1
	test("tree-diagram - [x150b1c6c6e15ce1f] Choose the correct tree diagram for three coin flips (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "n3heads",
		      "from": "rootB",
		      "style": "solid"
		    },
		    {
		      "to": "n2h1t",
		      "from": "rootB",
		      "style": "solid"
		    },
		    {
		      "to": "n1h2t",
		      "from": "rootB",
		      "style": "solid"
		    },
		    {
		      "to": "n3tails",
		      "from": "rootB",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "rootB",
		      "color": "#000000",
		      "label": "Start",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 50
		      }
		    },
		    {
		      "id": "n3heads",
		      "color": "#000000",
		      "label": "3 heads",
		      "style": "circled",
		      "position": {
		        "x": 70,
		        "y": 200
		      }
		    },
		    {
		      "id": "n2h1t",
		      "color": "#000000",
		      "label": "2 heads and 1 tail",
		      "style": "circled",
		      "position": {
		        "x": 170,
		        "y": 200
		      }
		    },
		    {
		      "id": "n1h2t",
		      "color": "#000000",
		      "label": "1 head and 2 tails",
		      "style": "circled",
		      "position": {
		        "x": 270,
		        "y": 200
		      }
		    },
		    {
		      "id": "n3tails",
		      "color": "#000000",
		      "label": "3 tails",
		      "style": "circled",
		      "position": {
		        "x": 370,
		        "y": 200
		      }
		    }
		  ],
		  "width": 440,
		  "height": 300,
		  "nodeRadius": 30,
		  "nodeFontSize": 11
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x150b1c6c6e15ce1f
	// Question: Choose the correct tree diagram for three coin flips
	// Widget key: image_2
	test("tree-diagram - [x150b1c6c6e15ce1f] Choose the correct tree diagram for three coin flips (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "h1",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "t1",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "hh2",
		      "from": "h1",
		      "style": "solid"
		    },
		    {
		      "to": "ht2",
		      "from": "h1",
		      "style": "solid"
		    },
		    {
		      "to": "th2",
		      "from": "t1",
		      "style": "solid"
		    },
		    {
		      "to": "tt2",
		      "from": "t1",
		      "style": "solid"
		    },
		    {
		      "to": "hhh3",
		      "from": "hh2",
		      "style": "solid"
		    },
		    {
		      "to": "hht3",
		      "from": "hh2",
		      "style": "solid"
		    },
		    {
		      "to": "hth3",
		      "from": "ht2",
		      "style": "solid"
		    },
		    {
		      "to": "htt3",
		      "from": "ht2",
		      "style": "solid"
		    },
		    {
		      "to": "thh3",
		      "from": "th2",
		      "style": "solid"
		    },
		    {
		      "to": "tht3",
		      "from": "th2",
		      "style": "solid"
		    },
		    {
		      "to": "tth3",
		      "from": "tt2",
		      "style": "solid"
		    },
		    {
		      "to": "ttt3",
		      "from": "tt2",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": "Start",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 30
		      }
		    },
		    {
		      "id": "h1",
		      "color": "#000000",
		      "label": "H",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 74
		      }
		    },
		    {
		      "id": "t1",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 74
		      }
		    },
		    {
		      "id": "hh2",
		      "color": "#000000",
		      "label": "H",
		      "style": "circled",
		      "position": {
		        "x": 70,
		        "y": 174
		      }
		    },
		    {
		      "id": "ht2",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 170,
		        "y": 174
		      }
		    },
		    {
		      "id": "th2",
		      "color": "#000000",
		      "label": "H",
		      "style": "circled",
		      "position": {
		        "x": 270,
		        "y": 174
		      }
		    },
		    {
		      "id": "tt2",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 370,
		        "y": 174
		      }
		    },
		    {
		      "id": "hhh3",
		      "color": "#000000",
		      "label": "H",
		      "style": "circled",
		      "position": {
		        "x": 45,
		        "y": 274
		      }
		    },
		    {
		      "id": "hht3",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 95,
		        "y": 274
		      }
		    },
		    {
		      "id": "hth3",
		      "color": "#000000",
		      "label": "H",
		      "style": "circled",
		      "position": {
		        "x": 145,
		        "y": 274
		      }
		    },
		    {
		      "id": "htt3",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 195,
		        "y": 274
		      }
		    },
		    {
		      "id": "thh3",
		      "color": "#000000",
		      "label": "H",
		      "style": "circled",
		      "position": {
		        "x": 245,
		        "y": 274
		      }
		    },
		    {
		      "id": "tht3",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 295,
		        "y": 274
		      }
		    },
		    {
		      "id": "tth3",
		      "color": "#000000",
		      "label": "H",
		      "style": "circled",
		      "position": {
		        "x": 345,
		        "y": 274
		      }
		    },
		    {
		      "id": "ttt3",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 395,
		        "y": 274
		      }
		    }
		  ],
		  "width": 440,
		  "height": 304,
		  "nodeRadius": 20,
		  "nodeFontSize": 14
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xba15989aa199a8fc
	// Question: Tree diagrams for color and size outcomes
	// Widget key: image_1
	test("tree-diagram - [xba15989aa199a8fc] Tree diagrams for color and size outcomes (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "node-g",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "node-o",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "node-y",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "node-g-l",
		      "from": "node-g",
		      "style": "solid"
		    },
		    {
		      "to": "node-g-s",
		      "from": "node-g",
		      "style": "solid"
		    },
		    {
		      "to": "node-o-l",
		      "from": "node-o",
		      "style": "solid"
		    },
		    {
		      "to": "node-o-s",
		      "from": "node-o",
		      "style": "solid"
		    },
		    {
		      "to": "node-y-l",
		      "from": "node-y",
		      "style": "solid"
		    },
		    {
		      "to": "node-y-s",
		      "from": "node-y",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": null,
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 20
		      }
		    },
		    {
		      "id": "node-g",
		      "color": "#000000",
		      "label": "G",
		      "style": "circled",
		      "position": {
		        "x": 86.8,
		        "y": 74
		      }
		    },
		    {
		      "id": "node-o",
		      "color": "#000000",
		      "label": "O",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 74
		      }
		    },
		    {
		      "id": "node-y",
		      "color": "#000000",
		      "label": "Y",
		      "style": "circled",
		      "position": {
		        "x": 353.2,
		        "y": 74
		      }
		    },
		    {
		      "id": "node-g-l",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 53.2,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-g-s",
		      "color": "#000000",
		      "label": "S",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-o-l",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 186.8,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-o-s",
		      "color": "#000000",
		      "label": "S",
		      "style": "circled",
		      "position": {
		        "x": 253.2,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-y-l",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-y-s",
		      "color": "#000000",
		      "label": "S",
		      "style": "circled",
		      "position": {
		        "x": 386.8,
		        "y": 174
		      }
		    }
		  ],
		  "width": 440,
		  "height": 304,
		  "nodeRadius": 20,
		  "nodeFontSize": 16
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xba15989aa199a8fc
	// Question: Tree diagrams for color and size outcomes
	// Widget key: image_2
	test("tree-diagram - [xba15989aa199a8fc] Tree diagrams for color and size outcomes (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "node-l",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "node-s",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "node-l-g",
		      "from": "node-l",
		      "style": "solid"
		    },
		    {
		      "to": "node-l-o",
		      "from": "node-l",
		      "style": "solid"
		    },
		    {
		      "to": "node-l-y",
		      "from": "node-l",
		      "style": "solid"
		    },
		    {
		      "to": "node-s-g",
		      "from": "node-s",
		      "style": "solid"
		    },
		    {
		      "to": "node-s-o",
		      "from": "node-s",
		      "style": "solid"
		    },
		    {
		      "to": "node-s-y",
		      "from": "node-s",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": null,
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 20
		      }
		    },
		    {
		      "id": "node-l",
		      "color": "#000000",
		      "label": "L",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 74
		      }
		    },
		    {
		      "id": "node-s",
		      "color": "#000000",
		      "label": "S",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 74
		      }
		    },
		    {
		      "id": "node-l-g",
		      "color": "#000000",
		      "label": "G",
		      "style": "circled",
		      "position": {
		        "x": 53.2,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-l-o",
		      "color": "#000000",
		      "label": "O",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-l-y",
		      "color": "#000000",
		      "label": "Y",
		      "style": "circled",
		      "position": {
		        "x": 186.8,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-s-g",
		      "color": "#000000",
		      "label": "G",
		      "style": "circled",
		      "position": {
		        "x": 253.2,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-s-o",
		      "color": "#000000",
		      "label": "O",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 174
		      }
		    },
		    {
		      "id": "node-s-y",
		      "color": "#000000",
		      "label": "Y",
		      "style": "circled",
		      "position": {
		        "x": 386.8,
		        "y": 174
		      }
		    }
		  ],
		  "width": 440,
		  "height": 304,
		  "nodeRadius": 20,
		  "nodeFontSize": 16
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa26f24ccdf07b97c
	// Question: Select the tree diagram for round-trip travel choices
	// Widget key: image_1
	test("tree-diagram - [xa26f24ccdf07b97c] Select the tree diagram for round-trip travel choices (1)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "b1",
		      "from": "r",
		      "style": "solid"
		    },
		    {
		      "to": "b2",
		      "from": "r",
		      "style": "solid"
		    },
		    {
		      "to": "c1",
		      "from": "b1",
		      "style": "solid"
		    },
		    {
		      "to": "c2",
		      "from": "b1",
		      "style": "solid"
		    },
		    {
		      "to": "c3",
		      "from": "b2",
		      "style": "solid"
		    },
		    {
		      "to": "c4",
		      "from": "b2",
		      "style": "solid"
		    },
		    {
		      "to": "t1",
		      "from": "c1",
		      "style": "solid"
		    },
		    {
		      "to": "t2",
		      "from": "c1",
		      "style": "solid"
		    },
		    {
		      "to": "t3",
		      "from": "c2",
		      "style": "solid"
		    },
		    {
		      "to": "t4",
		      "from": "c2",
		      "style": "solid"
		    },
		    {
		      "to": "t5",
		      "from": "c3",
		      "style": "solid"
		    },
		    {
		      "to": "t6",
		      "from": "c3",
		      "style": "solid"
		    },
		    {
		      "to": "t7",
		      "from": "c4",
		      "style": "solid"
		    },
		    {
		      "to": "t8",
		      "from": "c4",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "r",
		      "color": "#000000",
		      "label": null,
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 20
		      }
		    },
		    {
		      "id": "b1",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 74
		      }
		    },
		    {
		      "id": "b2",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 74
		      }
		    },
		    {
		      "id": "c1",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 70,
		        "y": 174
		      }
		    },
		    {
		      "id": "c2",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 170,
		        "y": 174
		      }
		    },
		    {
		      "id": "c3",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 270,
		        "y": 174
		      }
		    },
		    {
		      "id": "c4",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 370,
		        "y": 174
		      }
		    },
		    {
		      "id": "t1",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 45,
		        "y": 274
		      }
		    },
		    {
		      "id": "t2",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 95,
		        "y": 274
		      }
		    },
		    {
		      "id": "t3",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 145,
		        "y": 274
		      }
		    },
		    {
		      "id": "t4",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 195,
		        "y": 274
		      }
		    },
		    {
		      "id": "t5",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 245,
		        "y": 274
		      }
		    },
		    {
		      "id": "t6",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 295,
		        "y": 274
		      }
		    },
		    {
		      "id": "t7",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 345,
		        "y": 274
		      }
		    },
		    {
		      "id": "t8",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 395,
		        "y": 274
		      }
		    }
		  ],
		  "width": 440,
		  "height": 304,
		  "nodeRadius": 20,
		  "nodeFontSize": 16
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xa26f24ccdf07b97c
	// Question: Select the tree diagram for round-trip travel choices
	// Widget key: image_2
	test("tree-diagram - [xa26f24ccdf07b97c] Select the tree diagram for round-trip travel choices (2)", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "top_b",
		      "from": "r",
		      "style": "solid"
		    },
		    {
		      "to": "top_c",
		      "from": "r",
		      "style": "solid"
		    },
		    {
		      "to": "top_t",
		      "from": "r",
		      "style": "solid"
		    },
		    {
		      "to": "b_b",
		      "from": "top_b",
		      "style": "solid"
		    },
		    {
		      "to": "b_c",
		      "from": "top_b",
		      "style": "solid"
		    },
		    {
		      "to": "b_t",
		      "from": "top_b",
		      "style": "solid"
		    },
		    {
		      "to": "c_b",
		      "from": "top_c",
		      "style": "solid"
		    },
		    {
		      "to": "c_c",
		      "from": "top_c",
		      "style": "solid"
		    },
		    {
		      "to": "c_t",
		      "from": "top_c",
		      "style": "solid"
		    },
		    {
		      "to": "t_b",
		      "from": "top_t",
		      "style": "solid"
		    },
		    {
		      "to": "t_c",
		      "from": "top_t",
		      "style": "solid"
		    },
		    {
		      "to": "t_t",
		      "from": "top_t",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "r",
		      "color": "#000000",
		      "label": null,
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 20
		      }
		    },
		    {
		      "id": "top_b",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 86.8,
		        "y": 74
		      }
		    },
		    {
		      "id": "top_c",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 74
		      }
		    },
		    {
		      "id": "top_t",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 353.2,
		        "y": 74
		      }
		    },
		    {
		      "id": "b_b",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 42.4,
		        "y": 174
		      }
		    },
		    {
		      "id": "b_c",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 86.8,
		        "y": 174
		      }
		    },
		    {
		      "id": "b_t",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 131.2,
		        "y": 174
		      }
		    },
		    {
		      "id": "c_b",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 175.6,
		        "y": 174
		      }
		    },
		    {
		      "id": "c_c",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 174
		      }
		    },
		    {
		      "id": "c_t",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 264.4,
		        "y": 174
		      }
		    },
		    {
		      "id": "t_b",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 308.8,
		        "y": 174
		      }
		    },
		    {
		      "id": "t_c",
		      "color": "#000000",
		      "label": "C",
		      "style": "circled",
		      "position": {
		        "x": 353.2,
		        "y": 174
		      }
		    },
		    {
		      "id": "t_t",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 397.6,
		        "y": 174
		      }
		    }
		  ],
		  "width": 440,
		  "height": 304,
		  "nodeRadius": 20,
		  "nodeFontSize": 16
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: x8098a292aa874f61
	// Question: Identify the correct sample space display
	// Widget key: image_3
	test("tree-diagram - [x8098a292aa874f61] Identify the correct sample space display", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "W",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "B",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "T",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "W_M",
		      "from": "W",
		      "style": "solid"
		    },
		    {
		      "to": "W_E",
		      "from": "W",
		      "style": "solid"
		    },
		    {
		      "to": "B_M",
		      "from": "B",
		      "style": "solid"
		    },
		    {
		      "to": "B_E",
		      "from": "B",
		      "style": "solid"
		    },
		    {
		      "to": "T_M",
		      "from": "T",
		      "style": "solid"
		    },
		    {
		      "to": "T_E",
		      "from": "T",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": " ",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 17.65
		      }
		    },
		    {
		      "id": "W",
		      "color": "#000000",
		      "label": "W",
		      "style": "circled",
		      "position": {
		        "x": 86.8,
		        "y": 108.82
		      }
		    },
		    {
		      "id": "B",
		      "color": "#000000",
		      "label": "B",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 108.82
		      }
		    },
		    {
		      "id": "T",
		      "color": "#000000",
		      "label": "T",
		      "style": "circled",
		      "position": {
		        "x": 353.2,
		        "y": 108.82
		      }
		    },
		    {
		      "id": "W_M",
		      "color": "#000000",
		      "label": "M",
		      "style": "circled",
		      "position": {
		        "x": 53.2,
		        "y": 255.88
		      }
		    },
		    {
		      "id": "W_E",
		      "color": "#000000",
		      "label": "E",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 255.88
		      }
		    },
		    {
		      "id": "B_M",
		      "color": "#000000",
		      "label": "M",
		      "style": "circled",
		      "position": {
		        "x": 186.8,
		        "y": 255.88
		      }
		    },
		    {
		      "id": "B_E",
		      "color": "#000000",
		      "label": "E",
		      "style": "circled",
		      "position": {
		        "x": 253.2,
		        "y": 255.88
		      }
		    },
		    {
		      "id": "T_M",
		      "color": "#000000",
		      "label": "M",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 255.88
		      }
		    },
		    {
		      "id": "T_E",
		      "color": "#000000",
		      "label": "E",
		      "style": "circled",
		      "position": {
		        "x": 386.8,
		        "y": 255.88
		      }
		    }
		  ],
		  "width": 440,
		  "height": 300,
		  "nodeRadius": 20,
		  "nodeFontSize": 16
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

	// Extracted from question: xc17be1d52db777d5
	// Question: Choose the correct sample-space display
	// Widget key: image_1
	test("tree-diagram - [xc17be1d52db777d5] Choose the correct sample-space display", async () => {
		// Note: Database data may not match current library schemas exactly
		// Using runtime validation in generateWidget for flexibility
		const input = {
		  "type": "treeDiagram",
		  "edges": [
		    {
		      "to": "r_node",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "f_node",
		      "from": "root",
		      "style": "solid"
		    },
		    {
		      "to": "leaf_rw",
		      "from": "r_node",
		      "style": "solid"
		    },
		    {
		      "to": "leaf_rs",
		      "from": "r_node",
		      "style": "solid"
		    },
		    {
		      "to": "leaf_rg",
		      "from": "r_node",
		      "style": "solid"
		    },
		    {
		      "to": "leaf_rp",
		      "from": "r_node",
		      "style": "solid"
		    },
		    {
		      "to": "leaf_fw",
		      "from": "f_node",
		      "style": "solid"
		    },
		    {
		      "to": "leaf_fs",
		      "from": "f_node",
		      "style": "solid"
		    },
		    {
		      "to": "leaf_fg",
		      "from": "f_node",
		      "style": "solid"
		    },
		    {
		      "to": "leaf_fp",
		      "from": "f_node",
		      "style": "solid"
		    }
		  ],
		  "nodes": [
		    {
		      "id": "root",
		      "color": "#000000",
		      "label": " ",
		      "style": "circled",
		      "position": {
		        "x": 220,
		        "y": 30
		      }
		    },
		    {
		      "id": "r_node",
		      "color": "#000000",
		      "label": "R",
		      "style": "circled",
		      "position": {
		        "x": 120,
		        "y": 80
		      }
		    },
		    {
		      "id": "f_node",
		      "color": "#000000",
		      "label": "F",
		      "style": "circled",
		      "position": {
		        "x": 320,
		        "y": 80
		      }
		    },
		    {
		      "id": "leaf_rw",
		      "color": "#000000",
		      "label": "W",
		      "style": "circled",
		      "position": {
		        "x": 45,
		        "y": 240
		      }
		    },
		    {
		      "id": "leaf_rs",
		      "color": "#000000",
		      "label": "S",
		      "style": "circled",
		      "position": {
		        "x": 95,
		        "y": 240
		      }
		    },
		    {
		      "id": "leaf_rg",
		      "color": "#000000",
		      "label": "G",
		      "style": "circled",
		      "position": {
		        "x": 145,
		        "y": 240
		      }
		    },
		    {
		      "id": "leaf_rp",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 195,
		        "y": 240
		      }
		    },
		    {
		      "id": "leaf_fw",
		      "color": "#000000",
		      "label": "W",
		      "style": "circled",
		      "position": {
		        "x": 245,
		        "y": 240
		      }
		    },
		    {
		      "id": "leaf_fs",
		      "color": "#000000",
		      "label": "S",
		      "style": "circled",
		      "position": {
		        "x": 295,
		        "y": 240
		      }
		    },
		    {
		      "id": "leaf_fg",
		      "color": "#000000",
		      "label": "G",
		      "style": "circled",
		      "position": {
		        "x": 345,
		        "y": 240
		      }
		    },
		    {
		      "id": "leaf_fp",
		      "color": "#000000",
		      "label": "P",
		      "style": "circled",
		      "position": {
		        "x": 395,
		        "y": 240
		      }
		    }
		  ],
		  "width": 440,
		  "height": 300,
		  "nodeRadius": 20,
		  "nodeFontSize": 16
		} as unknown as WidgetInput

		// Generate the widget (includes runtime validation)
		const result = await errors.try(generateWidget(input as unknown as Widget))
		if (result.error) {
			// If widget generation fails, it likely means the database data doesn't match current schema
			logger.error("widget generation failed for treeDiagram", { 
				error: result.error,
				inputData: input
			})
			throw errors.wrap(result.error, "widget generation")
		}
		
		const svg = result.data
		expect(svg).toMatchSnapshot()
	})

})
