import * as fs from "node:fs/promises"
import * as path from "node:path"
import * as errors from "@superbuilders/errors"
import { inngest } from "@/inngest/client"
import { qti } from "@/lib/clients"
import { ErrQtiNotFound } from "@/lib/qti"
import { extractIdentifier, extractQtiStimulusBodyContent, extractTitle } from "@/lib/xml-utils"

export const ingestAssessmentStimulusOne = inngest.createFunction(
	{
		id: "ingest-assessment-stimulus-one",
		name: "Ingest One QTI Assessment Stimulus",
		concurrency: {
			limit: 100,
			key: "timeback"
		},
		retries: 3
	},
	{ event: "qti/assessment-stimulus.ingest.one" },
	async ({ event, logger }) => {
		const { courseSlug, identifier } = event.data
		if (!identifier) {
			logger.error("stimulus ingestion: missing identifier")
			return { identifier: null, status: "failed_no_id" }
		}

		// Load stimulus xml from disk
		const filePath = path.join(process.cwd(), "data", courseSlug, "qti", "assessmentStimuli.json")
		const readResult = await errors.try(fs.readFile(filePath, "utf-8"))
		if (readResult.error) {
			logger.error("file read", { file: filePath, error: readResult.error })
			throw errors.wrap(readResult.error, "file read")
		}
		// biome-ignore lint: Type assertion needed for loading raw data generated by QTI Generation flow
		const stimuli = JSON.parse(readResult.data) as Array<{ xml: string; metadata?: Record<string, unknown> }>
		const match = stimuli.find((s) => extractIdentifier(s.xml, "qti-assessment-stimulus") === identifier)
		if (!match) {
			logger.error("stimulus xml not found on disk", { identifier, file: filePath })
			throw errors.new("stimulus xml missing")
		}

		const title = extractTitle(match.xml)
		const content = extractQtiStimulusBodyContent(match.xml)

		if (!title || !content) {
			logger.error("Could not extract title or content from stimulus XML.", { identifier })
			return { identifier, status: "failed_parsing" }
		}

		logger.info("Ingesting assessment stimulus", { identifier, courseSlug })
		const payload = { identifier, title, content, metadata: match.metadata }

		const updateResult = await errors.try(qti.updateStimulus(identifier, payload))

		if (updateResult.error) {
			if (errors.is(updateResult.error, ErrQtiNotFound)) {
				logger.info("Stimulus not found, creating new.", { identifier })
				const createResult = await errors.try(qti.createStimulus(payload))
				if (createResult.error) {
					logger.error("Failed to create stimulus.", { identifier, error: createResult.error })
					throw createResult.error
				}
				logger.info("Successfully created stimulus.", { identifier })
				return { identifier, status: "created" }
			}
			logger.error("Failed to update stimulus.", { identifier, error: updateResult.error })
			throw updateResult.error
		}

		logger.info("Successfully updated stimulus.", { identifier })
		return { identifier, status: "updated" }
	}
)
