import {
	AdditionWithRegroupingPropsSchema,
	AreaModelMultiplicationPropsSchema,
	BarChartPropsSchema,
	BoxGridPropsSchema,
	DataTablePropsSchema,
	DivisionModelDiagramPropsSchema,
	EquivalentFractionModelPropsSchema,
	FactorizationDiagramPropsSchema,
	FractionFrequencyPlotPropsSchema,
	FractionModelDiagramPropsSchema,
	FractionMultiplicationModelPropsSchema,
	FractionNumberLinePropsSchema,
	NPolygonPropsSchema,
	NumberLinePropsSchema,
	PatternDiagramPropsSchema,
	NumberLineWithActionPropsSchema,
	ProtractorAngleDiagramPropsSchema,
	SimpleArrowPropsSchema,
	SingleFractionalModelDiagramPropsSchema,
	SubtractionWithRegroupingPropsSchema,
	TapeDiagramPropsSchema,
	VectorDiagramPropsSchema,
	VerticalArithmeticSetupPropsSchema
} from "@/lib/widgets/generators"

export const fourthGradeMathCollection = {
	name: "fourth-grade-math",
	schemas: {
		dataTable: DataTablePropsSchema,
		tapeDiagram: TapeDiagramPropsSchema,
		fractionModelDiagram: FractionModelDiagramPropsSchema,
		fractionMultiplicationModel: FractionMultiplicationModelPropsSchema,
		fractionFrequencyPlot: FractionFrequencyPlotPropsSchema,
		divisionModelDiagram: DivisionModelDiagramPropsSchema,
		factorizationDiagram: FactorizationDiagramPropsSchema,
		numberLine: NumberLinePropsSchema,
		numberLineWithAction: NumberLineWithActionPropsSchema,
		protractorAngleDiagram: ProtractorAngleDiagramPropsSchema,
		additionWithRegrouping: AdditionWithRegroupingPropsSchema,
		subtractionWithRegrouping: SubtractionWithRegroupingPropsSchema,
		verticalArithmeticSetup: VerticalArithmeticSetupPropsSchema,
		fractionNumberLine: FractionNumberLinePropsSchema,
		boxGrid: BoxGridPropsSchema,
		barChart: BarChartPropsSchema,
		equivalentFractionModel: EquivalentFractionModelPropsSchema,
		areaModelMultiplication: AreaModelMultiplicationPropsSchema,
		singleFractionalModelDiagram: SingleFractionalModelDiagramPropsSchema,
		simpleArrow: SimpleArrowPropsSchema,
		vectorDiagram: VectorDiagramPropsSchema,
		nPolygon: NPolygonPropsSchema,
		patternDiagram: PatternDiagramPropsSchema
	},
	widgetTypeKeys: [
		"dataTable",
		"tapeDiagram",
		"fractionModelDiagram",
		"fractionMultiplicationModel",
		"fractionFrequencyPlot",
		"divisionModelDiagram",
		"factorizationDiagram",
		"numberLine",
		"numberLineWithAction",
		"protractorAngleDiagram",
		"additionWithRegrouping",
		"subtractionWithRegrouping",
		"verticalArithmeticSetup",
		"fractionNumberLine",
		"boxGrid",
		"barChart",
		"equivalentFractionModel",
		"areaModelMultiplication",
		"singleFractionalModelDiagram",
		"simpleArrow",
		"vectorDiagram",
		"nPolygon",
		"patternDiagram"
	] as const
} as const
